// Grouped from 2 flat commands (Counter/slashcommand-counter-remove.js, Counter/slashcommand-counter-setup.js). Generated by scripts/group-commands.js.
const { ChatInputCommandInteraction } = require('discord.js');
const DiscordBot = require('../../client/DiscordBot');
const ApplicationCommand = require('../../structure/ApplicationCommand');
const { t, resolveLocale } = require('../../utils/i18n');
const { PermissionFlagsBits } = require('discord.js');
const { successEmbed, errorEmbed, infoEmbed } = require('../../utils/embeds');

const SUB_PERMS = {
    "counter-remove": "16",
    "counter-setup": "16",
};

const handlers = {
    "counter-remove": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const all = client.database.get('counters-' + interaction.guildId) || [];
        for (const c of all) { try { const ch = await client.channels.fetch(c.channelId).catch(() => null); await ch?.delete().catch(() => null); } catch {} }
        client.database.set('counters-' + interaction.guildId, []);
        return interaction.reply({ embeds: [successEmbed(locale, t('counter.removed', { locale }))] });
    },
    "counter-setup": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const { ChannelType } = require('discord.js');
        const type = interaction.options.getString('type', true);
        const g = interaction.guild;
        let label = type + ': 0';
        if (type === 'members') label = 'Members: ' + g.memberCount;
        if (type === 'bots') label = 'Bots: ' + g.members.cache.filter(m => m.user.bot).size;
        if (type === 'roles') label = 'Roles: ' + g.roles.cache.size;
        const ch = await g.channels.create({ name: label, type: ChannelType.GuildVoice });
        const all = client.database.get('counters-' + interaction.guildId) || [];
        all.push({ channelId: ch.id, type });
        client.database.set('counters-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('counter.ok', { locale }) + ' TODO: periodic update engine.')] });
    },
};

module.exports = new ApplicationCommand({
    command: {
        name: "counter", description: "🔢 Member counters.", type: 1,
        description_localizations: { 'pt-BR': "🔢 Contadores de membros." },
        default_member_permissions: "16",
        options: [
            {
                name: "counter-remove",
                description: "🔢 Removes counter channels.",
                description_localizations: {"pt-BR":"🔢 Remove canais de contador."},
                type: 1,
                options: [],
            },
            {
                name: "counter-setup",
                description: "🔢 Creates static counter voice channels.",
                description_localizations: {"pt-BR":"🔢 Cria canais de voz com contadores."},
                type: 1,
                options: [{"name":"type","name_localizations":{"pt-BR":"tipo"},"description":"members/bots/roles","description_localizations":{"pt-BR":"membros/bots/cargos"},"type":3,"required":true,"choices":[{"name":"members","value":"members"},{"name":"bots","value":"bots"},{"name":"roles","value":"roles"}]}],
            },
        ],
    },
    /**
     * @param {DiscordBot} client
     * @param {ChatInputCommandInteraction} interaction
     */
    run: async (client, interaction) => {
        const sub = interaction.options.getSubcommand();
        const need = SUB_PERMS[sub];
        if (need) {
            let ok = false;
            try { ok = !!interaction.memberPermissions && interaction.memberPermissions.has(BigInt(need)); } catch { ok = false; }
            if (!ok) {
                const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
                return interaction.reply({ content: t('handler.missing_permissions', { locale }), ephemeral: true });
            }
        }
        const fn = handlers[sub];
        if (!fn) {
            return interaction.reply({ content: 'Unknown subcommand: ' + sub, ephemeral: true });
        }
        return fn(client, interaction);
    },
}).toJSON();
