// Grouped from 2 flat commands (Logs/slashcommand-log-ignore.js, Logs/slashcommand-setlog.js). Generated by scripts/group-commands.js.
const { ChatInputCommandInteraction } = require('discord.js');
const DiscordBot = require('../../client/DiscordBot');
const ApplicationCommand = require('../../structure/ApplicationCommand');
const { t, resolveLocale } = require('../../utils/i18n');
const { PermissionFlagsBits } = require('discord.js');
const { successEmbed, errorEmbed, infoEmbed } = require('../../utils/embeds');

const SUB_PERMS = {
    "log-ignore": "32",
    "setlog": "32",
};

const handlers = {
    "log-ignore": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const ch = interaction.options.getChannel('channel', true);
        const arr = client.database.get('logignore-' + interaction.guildId) || [];
        const i = arr.indexOf(ch.id);
        if (i >= 0) arr.splice(i, 1); else arr.push(ch.id);
        client.database.set('logignore-' + interaction.guildId, arr);
        return interaction.reply({ embeds: [successEmbed(locale, t('logignore.ok', { locale, vars: { ch: ch.id } }))] });
    },
    "setlog": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const type = interaction.options.getString('type', true);
        const ch = interaction.options.getChannel('channel', true);
        const all = client.database.get('logs-' + interaction.guildId) || {};
        all[type] = ch.id;
        client.database.set('logs-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('setlog.ok', { locale, vars: { type, ch: ch.id } }))] });
    },
};

module.exports = new ApplicationCommand({
    command: {
        name: "logs", description: "📝 Logging configuration.", type: 1,
        description_localizations: { 'pt-BR': "📝 Configuração de logs." },
        default_member_permissions: "32",
        options: [
            {
                name: "log-ignore",
                description: "📝 Toggles ignoring a channel in logs.",
                description_localizations: {"pt-BR":"📝 Alterna ignorar um canal nos logs."},
                type: 1,
                options: [{"name":"channel","name_localizations":{"pt-BR":"canal"},"description":"Channel","description_localizations":{"pt-BR":"Canal"},"type":7,"required":true}],
            },
            {
                name: "setlog",
                description: "📝 Sets the log channel for a type.",
                description_localizations: {"pt-BR":"📝 Define canal de log por tipo."},
                type: 1,
                options: [{"name":"type","name_localizations":{"pt-BR":"tipo"},"description":"mod/message/member/voice","description_localizations":{"pt-BR":"mod/mensagem/membro/voz"},"type":3,"required":true,"choices":[{"name":"mod","value":"mod"},{"name":"message","value":"message"},{"name":"member","value":"member"},{"name":"voice","value":"voice"}]},{"name":"channel","name_localizations":{"pt-BR":"canal"},"description":"Channel","description_localizations":{"pt-BR":"Canal"},"type":7,"required":true}],
            },
        ],
    },
    /**
     * @param {DiscordBot} client
     * @param {ChatInputCommandInteraction} interaction
     */
    run: async (client, interaction) => {
        const sub = interaction.options.getSubcommand();
        const need = SUB_PERMS[sub];
        if (need) {
            let ok = false;
            try { ok = !!interaction.memberPermissions && interaction.memberPermissions.has(BigInt(need)); } catch { ok = false; }
            if (!ok) {
                const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
                return interaction.reply({ content: t('handler.missing_permissions', { locale }), ephemeral: true });
            }
        }
        const fn = handlers[sub];
        if (!fn) {
            return interaction.reply({ content: 'Unknown subcommand: ' + sub, ephemeral: true });
        }
        return fn(client, interaction);
    },
}).toJSON();
