// Grouped from 18 flat commands (Economy/slashcommand-balance.js, Economy/slashcommand-buy.js, Economy/slashcommand-crime.js, Economy/slashcommand-daily.js, Economy/slashcommand-deposit.js, Economy/slashcommand-economy-reset.js, Economy/slashcommand-gift.js, Economy/slashcommand-inventory.js, Economy/slashcommand-money-leaderboard.js, Economy/slashcommand-pay.js, Economy/slashcommand-rob.js, Economy/slashcommand-shop-add.js, Economy/slashcommand-shop-edit.js, Economy/slashcommand-shop-remove.js, Economy/slashcommand-shop.js, Economy/slashcommand-use.js, Economy/slashcommand-withdraw.js, Economy/slashcommand-work.js). Generated by scripts/group-commands.js.
const { ChatInputCommandInteraction } = require('discord.js');
const DiscordBot = require('../../client/DiscordBot');
const ApplicationCommand = require('../../structure/ApplicationCommand');
const { t, resolveLocale } = require('../../utils/i18n');
const { successEmbed, errorEmbed, infoEmbed } = require('../../utils/embeds');
const { PermissionFlagsBits } = require('discord.js');

const SUB_PERMS = {
    "economy-reset": "32",
    "shop-add": "32",
    "shop-edit": "32",
    "shop-remove": "32",
};

const handlers = {
    "balance": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const cur = client.database.get('currency-' + interaction.guildId) || 'coins';
        const eco = client.database.get('eco-' + interaction.guildId) || {};
        const bal = (id) => eco[id] || (eco[id] = { wallet: 0, bank: 0 });
        const save = () => client.database.set('eco-' + interaction.guildId, eco);
        const user = interaction.options.getUser('user') || interaction.user;
        const b = bal(user.id);
        return interaction.reply({ embeds: [infoEmbed(locale, t('eco.balance', { locale, vars: { user: user.tag, wallet: b.wallet, bank: b.bank, cur } }))] });
    },
    "buy": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const cur = client.database.get('currency-' + interaction.guildId) || 'coins';
        const eco = client.database.get('eco-' + interaction.guildId) || {};
        const bal = (id) => eco[id] || (eco[id] = { wallet: 0, bank: 0 });
        const save = () => client.database.set('eco-' + interaction.guildId, eco);
        const item = interaction.options.getString('item', true);
        const shop = client.database.get('shop-' + interaction.guildId) || [];
        const s = shop.find(x => x.name.toLowerCase() === item.toLowerCase());
        if (!s) return interaction.reply({ embeds: [errorEmbed(locale, t('shop.notfound', { locale }))], ephemeral: true });
        const b = bal(interaction.user.id);
        if (b.wallet < s.price) return interaction.reply({ embeds: [errorEmbed(locale, t('eco.no_funds', { locale }))], ephemeral: true });
        b.wallet -= s.price; save();
        const inv = client.database.get('inv-' + interaction.guildId + '-' + interaction.user.id) || [];
        inv.push(s.name);
        client.database.set('inv-' + interaction.guildId + '-' + interaction.user.id, inv);
        return interaction.reply({ embeds: [successEmbed(locale, t('shop.bought', { locale, vars: { item: s.name } }))] });
    },
    "crime": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const cur = client.database.get('currency-' + interaction.guildId) || 'coins';
        const eco = client.database.get('eco-' + interaction.guildId) || {};
        const bal = (id) => eco[id] || (eco[id] = { wallet: 0, bank: 0 });
        const save = () => client.database.set('eco-' + interaction.guildId, eco);
        const amt = -100 + Math.floor(Math.random() * (250 - -100));
        bal(interaction.user.id).wallet = Math.max(0, bal(interaction.user.id).wallet + amt); save();
        return interaction.reply({ embeds: [infoEmbed(locale, t('eco.crime', { locale, vars: { amt: Math.abs(amt), cur, good: amt >= 0 } }))] });
    },
    "daily": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const cur = client.database.get('currency-' + interaction.guildId) || 'coins';
        const eco = client.database.get('eco-' + interaction.guildId) || {};
        const bal = (id) => eco[id] || (eco[id] = { wallet: 0, bank: 0 });
        const save = () => client.database.set('eco-' + interaction.guildId, eco);
        const last = client.database.get('daily-' + interaction.guildId + '-' + interaction.user.id) || 0;
        if (Date.now() - last < 86400000) return interaction.reply({ embeds: [errorEmbed(locale, t('eco.daily_cd', { locale, vars: { h: Math.ceil((86400000 - (Date.now() - last)) / 3600000) } }))] , ephemeral: true });
        const amt = 100 + Math.floor(Math.random() * 100);
        bal(interaction.user.id).wallet += amt; save();
        client.database.set('daily-' + interaction.guildId + '-' + interaction.user.id, Date.now());
        return interaction.reply({ embeds: [successEmbed(locale, t('eco.daily', { locale, vars: { amt, cur } }))] });
    },
    "deposit": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const cur = client.database.get('currency-' + interaction.guildId) || 'coins';
        const eco = client.database.get('eco-' + interaction.guildId) || {};
        const bal = (id) => eco[id] || (eco[id] = { wallet: 0, bank: 0 });
        const save = () => client.database.set('eco-' + interaction.guildId, eco);
        const amount = interaction.options.getInteger('amount', true);
        if (amount < 1) return interaction.reply({ embeds: [errorEmbed(locale, t('eco.invalid_amt', { locale }))], ephemeral: true });
        const b = bal(interaction.user.id);
        if (b.wallet < amount) return interaction.reply({ embeds: [errorEmbed(locale, t("eco.no_funds", { locale }))], ephemeral: true }); b.wallet -= amount; b.bank += amount;
        save();
        return interaction.reply({ embeds: [successEmbed(locale, t('eco.deposit', { locale, vars: { amount, cur } }))] });
    },
    "economy-reset": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        client.database.set('eco-' + interaction.guildId, {});
        return interaction.reply({ embeds: [successEmbed(locale, t('eco.reset', { locale }))] });
    },
    "gift": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user', true);
        const item = interaction.options.getString('item', true);
        const inv = client.database.get('inv-' + interaction.guildId + '-' + interaction.user.id) || [];
        const i = inv.indexOf(item);
        if (i < 0) return interaction.reply({ embeds: [errorEmbed(locale, t('eco.no_item', { locale }))], ephemeral: true });
        inv.splice(i, 1);
        client.database.set('inv-' + interaction.guildId + '-' + interaction.user.id, inv);
        const tinv = client.database.get('inv-' + interaction.guildId + '-' + user.id) || [];
        tinv.push(item);
        client.database.set('inv-' + interaction.guildId + '-' + user.id, tinv);
        return interaction.reply({ embeds: [successEmbed(locale, t('eco.gifted', { locale, vars: { item, user: user.tag } }))] });
    },
    "inventory": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user') || interaction.user;
        const inv = client.database.get('inv-' + interaction.guildId + '-' + user.id) || [];
        if (!inv.length) return interaction.reply({ embeds: [infoEmbed(locale, t('inv.empty', { locale }))], ephemeral: true });
        return interaction.reply({ embeds: [infoEmbed(locale, inv.join(', ').slice(0, 3000))] });
    },
    "money-leaderboard": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const eco = client.database.get('eco-' + interaction.guildId) || {};
        const top = Object.entries(eco).sort((a, b) => ((b[1].wallet || 0) + (b[1].bank || 0)) - ((a[1].wallet || 0) + (a[1].bank || 0))).slice(0, 10);
        if (!top.length) return interaction.reply({ embeds: [infoEmbed(locale, t('moneylb.empty', { locale }))], ephemeral: true });
        return interaction.reply({ embeds: [infoEmbed(locale, top.map(([id, b], i) => (i + 1) + '. <@' + id + '> — ' + ((b.wallet || 0) + (b.bank || 0))).join('\n'))] });
    },
    "pay": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const cur = client.database.get('currency-' + interaction.guildId) || 'coins';
        const eco = client.database.get('eco-' + interaction.guildId) || {};
        const bal = (id) => eco[id] || (eco[id] = { wallet: 0, bank: 0 });
        const save = () => client.database.set('eco-' + interaction.guildId, eco);
        const user = interaction.options.getUser('user', true);
        const amount = interaction.options.getInteger('amount', true);
        if (amount < 1) return interaction.reply({ embeds: [errorEmbed(locale, t('eco.invalid_amt', { locale }))], ephemeral: true });
        const mb = bal(interaction.user.id);
        if (mb.wallet < amount) return interaction.reply({ embeds: [errorEmbed(locale, t('eco.no_funds', { locale }))], ephemeral: true });
        mb.wallet -= amount; bal(user.id).wallet += amount; save();
        return interaction.reply({ embeds: [successEmbed(locale, t('eco.paid', { locale, vars: { amount, cur, user: user.tag } }))] });
    },
    "rob": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const cur = client.database.get('currency-' + interaction.guildId) || 'coins';
        const eco = client.database.get('eco-' + interaction.guildId) || {};
        const bal = (id) => eco[id] || (eco[id] = { wallet: 0, bank: 0 });
        const save = () => client.database.set('eco-' + interaction.guildId, eco);
        const user = interaction.options.getUser('user', true);
        if (user.id === interaction.user.id) return interaction.reply({ embeds: [errorEmbed(locale, t('eco.rob_self', { locale }))], ephemeral: true });
        const tb = bal(user.id), mb = bal(interaction.user.id);
        if (tb.wallet < 50) return interaction.reply({ embeds: [errorEmbed(locale, t('eco.rob_poor', { locale }))], ephemeral: true });
        if (Math.random() < 0.5) { const amt = Math.min(tb.wallet, 20 + Math.floor(Math.random() * 80)); tb.wallet -= amt; mb.wallet += amt; save(); return interaction.reply({ embeds: [successEmbed(locale, t('eco.rob_ok', { locale, vars: { amt, cur } }))] }); }
        const fine = Math.min(mb.wallet, 50); mb.wallet -= fine; save();
        return interaction.reply({ embeds: [errorEmbed(locale, t('eco.rob_fail', { locale, vars: { fine, cur } }))] });
    },
    "shop": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const cur2 = client.database.get('currency-' + interaction.guildId) || 'coins';
        const shop = client.database.get('shop-' + interaction.guildId) || [];
        if (!shop.length) return interaction.reply({ embeds: [infoEmbed(locale, t('shop.empty', { locale }))], ephemeral: true });
        return interaction.reply({ embeds: [infoEmbed(locale, shop.map(i => '**' + i.name + '** — ' + i.price + ' ' + cur2).join('\n'))] });
    },
    "shop-add": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const item = interaction.options.getString('item', true);
        const price = interaction.options.getInteger('price', true);
        const shop = client.database.get('shop-' + interaction.guildId) || [];
        shop.push({ name: item, price });
        client.database.set('shop-' + interaction.guildId, shop);
        return interaction.reply({ embeds: [successEmbed(locale, t('shop.added', { locale, vars: { item } }))] });
    },
    "shop-edit": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const item = interaction.options.getString('item', true);
        const price = interaction.options.getInteger('price', true);
        const shop = client.database.get('shop-' + interaction.guildId) || [];
        const s = shop.find(x => x.name.toLowerCase() === item.toLowerCase());
        if (!s) return interaction.reply({ embeds: [errorEmbed(locale, t('shop.notfound', { locale }))], ephemeral: true });
        s.price = price;
        client.database.set('shop-' + interaction.guildId, shop);
        return interaction.reply({ embeds: [successEmbed(locale, t('shop.edited', { locale, vars: { item } }))] });
    },
    "shop-remove": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const item = interaction.options.getString('item', true);
        const shop = (client.database.get('shop-' + interaction.guildId) || []).filter(x => x.name.toLowerCase() !== item.toLowerCase());
        client.database.set('shop-' + interaction.guildId, shop);
        return interaction.reply({ embeds: [successEmbed(locale, t('shop.removed', { locale, vars: { item } }))] });
    },
    "use": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const item = interaction.options.getString('item', true);
        const inv = client.database.get('inv-' + interaction.guildId + '-' + interaction.user.id) || [];
        const i = inv.indexOf(item);
        if (i < 0) return interaction.reply({ embeds: [errorEmbed(locale, t('eco.no_item', { locale }))], ephemeral: true });
        inv.splice(i, 1);
        client.database.set('inv-' + interaction.guildId + '-' + interaction.user.id, inv);
        return interaction.reply({ embeds: [successEmbed(locale, t('use.ok', { locale, vars: { item } }))] });
    },
    "withdraw": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const cur = client.database.get('currency-' + interaction.guildId) || 'coins';
        const eco = client.database.get('eco-' + interaction.guildId) || {};
        const bal = (id) => eco[id] || (eco[id] = { wallet: 0, bank: 0 });
        const save = () => client.database.set('eco-' + interaction.guildId, eco);
        const amount = interaction.options.getInteger('amount', true);
        if (amount < 1) return interaction.reply({ embeds: [errorEmbed(locale, t('eco.invalid_amt', { locale }))], ephemeral: true });
        const b = bal(interaction.user.id);
        if (b.bank < amount) return interaction.reply({ embeds: [errorEmbed(locale, t("eco.no_funds", { locale }))], ephemeral: true }); b.bank -= amount; b.wallet += amount;
        save();
        return interaction.reply({ embeds: [successEmbed(locale, t('eco.withdraw', { locale, vars: { amount, cur } }))] });
    },
    "work": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const cur = client.database.get('currency-' + interaction.guildId) || 'coins';
        const eco = client.database.get('eco-' + interaction.guildId) || {};
        const bal = (id) => eco[id] || (eco[id] = { wallet: 0, bank: 0 });
        const save = () => client.database.set('eco-' + interaction.guildId, eco);
        const amt = 50 + Math.floor(Math.random() * (150 - 50));
        bal(interaction.user.id).wallet = Math.max(0, bal(interaction.user.id).wallet + amt); save();
        return interaction.reply({ embeds: [infoEmbed(locale, t('eco.work', { locale, vars: { amt: Math.abs(amt), cur, good: amt >= 0 } }))] });
    },
};

module.exports = new ApplicationCommand({
    command: {
        name: "eco", description: "💰 Economy commands.", type: 1,
        description_localizations: { 'pt-BR': "💰 Comandos de economia." },
        options: [
            {
                name: "balance",
                description: "💰 Shows wallet/bank balance.",
                description_localizations: {"pt-BR":"💰 Mostra saldo (carteira/banco)."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Member","description_localizations":{"pt-BR":"Membro"},"type":6}],
            },
            {
                name: "buy",
                description: "🛒 Buys a shop item.",
                description_localizations: {"pt-BR":"🛒 Compra item da loja."},
                type: 1,
                options: [{"name":"item","description":"Item name","description_localizations":{"pt-BR":"Nome do item"},"type":3,"required":true}],
            },
            {
                name: "crime",
                description: "💰 Commit a crime (risky).",
                description_localizations: {"pt-BR":"💰 Comete crime (arriscado)."},
                type: 1,
                options: [],
            },
            {
                name: "daily",
                description: "💰 Claims daily reward (24h cooldown).",
                description_localizations: {"pt-BR":"💰 Resgata recompensa diária (24h)."},
                type: 1,
                options: [],
            },
            {
                name: "deposit",
                description: "💰 Deposits wallet into bank.",
                description_localizations: {"pt-BR":"💰 Deposita carteira no banco."},
                type: 1,
                options: [{"name":"amount","name_localizations":{"pt-BR":"quantidade"},"description":"Amount","description_localizations":{"pt-BR":"Quantidade"},"type":4,"required":true}],
            },
            {
                name: "economy-reset",
                description: "💰 Resets the server economy.",
                description_localizations: {"pt-BR":"💰 Reseta a economia do servidor."},
                type: 1,
                options: [],
            },
            {
                name: "gift",
                description: "💰 Gifts an inventory item.",
                description_localizations: {"pt-BR":"💰 Presenteia um item do inventário."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Member","description_localizations":{"pt-BR":"Membro"},"type":6,"required":true},{"name":"item","description":"Item name","description_localizations":{"pt-BR":"Nome do item"},"type":3,"required":true}],
            },
            {
                name: "inventory",
                description: "🎒 Shows inventory.",
                description_localizations: {"pt-BR":"🎒 Mostra inventário."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Member","description_localizations":{"pt-BR":"Membro"},"type":6}],
            },
            {
                name: "money-leaderboard",
                description: "💰 Money leaderboard.",
                description_localizations: {"pt-BR":"💰 Ranking de dinheiro."},
                type: 1,
                options: [],
            },
            {
                name: "pay",
                description: "💰 Pays coins to a member.",
                description_localizations: {"pt-BR":"💰 Paga moedas a um membro."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Member","description_localizations":{"pt-BR":"Membro"},"type":6,"required":true},{"name":"amount","name_localizations":{"pt-BR":"quantidade"},"description":"Amount","description_localizations":{"pt-BR":"Quantidade"},"type":4,"required":true}],
            },
            {
                name: "rob",
                description: "💰 Robs a member wallet (risky).",
                description_localizations: {"pt-BR":"💰 Rouba carteira de membro (arriscado)."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Target","description_localizations":{"pt-BR":"Alvo"},"type":6,"required":true}],
            },
            {
                name: "shop",
                description: "🛒 Shows the shop.",
                description_localizations: {"pt-BR":"🛒 Mostra a loja."},
                type: 1,
                options: [],
            },
            {
                name: "shop-add",
                description: "🛒 Adds a shop item.",
                description_localizations: {"pt-BR":"🛒 Adiciona item à loja."},
                type: 1,
                options: [{"name":"item","description":"Item name","description_localizations":{"pt-BR":"Nome do item"},"type":3,"required":true},{"name":"price","name_localizations":{"pt-BR":"preco"},"description":"Price","description_localizations":{"pt-BR":"Preço"},"type":4,"required":true}],
            },
            {
                name: "shop-edit",
                description: "🛒 Edits a shop item price.",
                description_localizations: {"pt-BR":"🛒 Edita preço de item."},
                type: 1,
                options: [{"name":"item","description":"Item name","description_localizations":{"pt-BR":"Nome do item"},"type":3,"required":true},{"name":"price","name_localizations":{"pt-BR":"preco"},"description":"Price","description_localizations":{"pt-BR":"Preço"},"type":4,"required":true}],
            },
            {
                name: "shop-remove",
                description: "🛒 Removes a shop item.",
                description_localizations: {"pt-BR":"🛒 Remove item da loja."},
                type: 1,
                options: [{"name":"item","description":"Item name","description_localizations":{"pt-BR":"Nome do item"},"type":3,"required":true}],
            },
            {
                name: "use",
                description: "🎒 Uses an inventory item.",
                description_localizations: {"pt-BR":"🎒 Usa um item do inventário."},
                type: 1,
                options: [{"name":"item","description":"Item name","description_localizations":{"pt-BR":"Nome do item"},"type":3,"required":true}],
            },
            {
                name: "withdraw",
                description: "💰 Withdraws bank into wallet.",
                description_localizations: {"pt-BR":"💰 Saca do banco p/ carteira."},
                type: 1,
                options: [{"name":"amount","name_localizations":{"pt-BR":"quantidade"},"description":"Amount","description_localizations":{"pt-BR":"Quantidade"},"type":4,"required":true}],
            },
            {
                name: "work",
                description: "💰 Work for coins.",
                description_localizations: {"pt-BR":"💰 Trabalha por moedas."},
                type: 1,
                options: [],
            },
        ],
    },
    /**
     * @param {DiscordBot} client
     * @param {ChatInputCommandInteraction} interaction
     */
    run: async (client, interaction) => {
        const sub = interaction.options.getSubcommand();
        const need = SUB_PERMS[sub];
        if (need) {
            let ok = false;
            try { ok = !!interaction.memberPermissions && interaction.memberPermissions.has(BigInt(need)); } catch { ok = false; }
            if (!ok) {
                const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
                return interaction.reply({ content: t('handler.missing_permissions', { locale }), ephemeral: true });
            }
        }
        const fn = handlers[sub];
        if (!fn) {
            return interaction.reply({ content: 'Unknown subcommand: ' + sub, ephemeral: true });
        }
        return fn(client, interaction);
    },
}).toJSON();
