// Grouped from 6 flat commands (Automod/slashcommand-automod-action.js, Automod/slashcommand-automod-exempt.js, Automod/slashcommand-automod.js, Automod/slashcommand-badword-add.js, Automod/slashcommand-badword-list.js, Automod/slashcommand-badword-remove.js). Generated by scripts/group-commands.js.
const { ChatInputCommandInteraction } = require('discord.js');
const DiscordBot = require('../../client/DiscordBot');
const ApplicationCommand = require('../../structure/ApplicationCommand');
const { t, resolveLocale } = require('../../utils/i18n');
const { PermissionFlagsBits } = require('discord.js');
const { successEmbed, errorEmbed, infoEmbed } = require('../../utils/embeds');

const SUB_PERMS = {
    "automod": "32",
    "automod-action": "32",
    "automod-exempt": "32",
    "badword-add": "32",
    "badword-list": "32",
    "badword-remove": "32",
};

const handlers = {
    "automod": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const rule = interaction.options.getString('rule', true);
        const state = interaction.options.getString('state', true) === 'on';
        const all = client.database.get('automod-' + interaction.guildId) || {};
        all[rule] = { enabled: state };
        client.database.set('automod-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('automod.ok', { locale, vars: { rule, state: state ? 'on' : 'off' } }) + ' TODO: filter engine on message.')] });
    },
    "automod-action": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const action = interaction.options.getString('action', true);
        client.database.set('automod-action-' + interaction.guildId, action);
        return interaction.reply({ embeds: [successEmbed(locale, t('automod.action', { locale, vars: { action } }))] });
    },
    "automod-exempt": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const role = interaction.options.getRole('role');
        const ch = interaction.options.getChannel('channel');
        const all = client.database.get('automod-exempt-' + interaction.guildId) || { roles: [], channels: [] };
        if (role) { const i = all.roles.indexOf(role.id); if (i >= 0) all.roles.splice(i, 1); else all.roles.push(role.id); }
        if (ch) { const i = all.channels.indexOf(ch.id); if (i >= 0) all.channels.splice(i, 1); else all.channels.push(ch.id); }
        client.database.set('automod-exempt-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('automod.exempt', { locale }))] });
    },
    "badword-add": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const word = interaction.options.getString('word', true).toLowerCase();
        const arr = client.database.get('badwords-' + interaction.guildId) || [];
        if (!arr.includes(word)) arr.push(word);
        client.database.set('badwords-' + interaction.guildId, arr);
        return interaction.reply({ embeds: [successEmbed(locale, t('badword.added', { locale, vars: { word } }))] });
    },
    "badword-list": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const arr = client.database.get('badwords-' + interaction.guildId) || [];
        if (!arr.length) return interaction.reply({ embeds: [infoEmbed(locale, t('badword.empty', { locale }))], ephemeral: true });
        return interaction.reply({ embeds: [infoEmbed(locale, arr.join(', ').slice(0, 3500))] });
    },
    "badword-remove": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const word = interaction.options.getString('word', true).toLowerCase();
        client.database.set('badwords-' + interaction.guildId, (client.database.get('badwords-' + interaction.guildId) || []).filter(w => w !== word));
        return interaction.reply({ embeds: [successEmbed(locale, t('badword.removed', { locale, vars: { word } }))] });
    },
};

module.exports = new ApplicationCommand({
    command: {
        name: "automod", description: "🛡️ Automod configuration.", type: 1,
        description_localizations: { 'pt-BR': "🛡️ Configuração do automod." },
        default_member_permissions: "32",
        options: [
            {
                name: "automod",
                description: "🛡️ Toggles an automod rule.",
                description_localizations: {"pt-BR":"🛡️ Liga/desliga regra do automod."},
                type: 1,
                options: [{"name":"rule","name_localizations":{"pt-BR":"regra"},"description":"spam/invite/link/caps/badwords","description_localizations":{"pt-BR":"spam/convite/link/caps/badwords"},"type":3,"required":true,"choices":[{"name":"spam","value":"spam"},{"name":"invite","value":"invite"},{"name":"link","value":"link"},{"name":"caps","value":"caps"},{"name":"badwords","value":"badwords"}]},{"name":"state","name_localizations":{"pt-BR":"estado"},"description":"on/off","description_localizations":{"pt-BR":"on/off"},"type":3,"required":true,"choices":[{"name":"on","value":"on"},{"name":"off","value":"off"}]}],
            },
            {
                name: "automod-action",
                description: "🛡️ Sets automod punishment.",
                description_localizations: {"pt-BR":"🛡️ Define punição do automod."},
                type: 1,
                options: [{"name":"action","name_localizations":{"pt-BR":"acao"},"description":"delete/warn/timeout","description_localizations":{"pt-BR":"apagar/advertir/timeout"},"type":3,"required":true,"choices":[{"name":"delete","value":"delete"},{"name":"warn","value":"warn"},{"name":"timeout","value":"timeout"}]}],
            },
            {
                name: "automod-exempt",
                description: "🛡️ Toggles exempt role/channel.",
                description_localizations: {"pt-BR":"🛡️ Alterna isenção de cargo/canal."},
                type: 1,
                options: [{"name":"role","name_localizations":{"pt-BR":"cargo"},"description":"Role","description_localizations":{"pt-BR":"Cargo"},"type":8},{"name":"channel","name_localizations":{"pt-BR":"canal"},"description":"Channel","description_localizations":{"pt-BR":"Canal"},"type":7}],
            },
            {
                name: "badword-add",
                description: "🚫 Adds a bad word.",
                description_localizations: {"pt-BR":"🚫 Adiciona palavra proibida."},
                type: 1,
                options: [{"name":"word","description":"Word","description_localizations":{"pt-BR":"Palavra"},"type":3,"required":true}],
            },
            {
                name: "badword-list",
                description: "🚫 Lists bad words.",
                description_localizations: {"pt-BR":"🚫 Lista palavras proibidas."},
                type: 1,
                options: [],
            },
            {
                name: "badword-remove",
                description: "🚫 Removes a bad word.",
                description_localizations: {"pt-BR":"🚫 Remove palavra proibida."},
                type: 1,
                options: [{"name":"word","description":"Word","description_localizations":{"pt-BR":"Palavra"},"type":3,"required":true}],
            },
        ],
    },
    /**
     * @param {DiscordBot} client
     * @param {ChatInputCommandInteraction} interaction
     */
    run: async (client, interaction) => {
        const sub = interaction.options.getSubcommand();
        const need = SUB_PERMS[sub];
        if (need) {
            let ok = false;
            try { ok = !!interaction.memberPermissions && interaction.memberPermissions.has(BigInt(need)); } catch { ok = false; }
            if (!ok) {
                const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
                return interaction.reply({ content: t('handler.missing_permissions', { locale }), ephemeral: true });
            }
        }
        const fn = handlers[sub];
        if (!fn) {
            return interaction.reply({ content: 'Unknown subcommand: ' + sub, ephemeral: true });
        }
        return fn(client, interaction);
    },
}).toJSON();
