// Grouped from 11 flat commands (Tags/slashcommand-tag-create.js, Tags/slashcommand-tag-delete.js, Tags/slashcommand-tag-edit.js, Tags/slashcommand-tag-info.js, Tags/slashcommand-tag-list.js, Remind/slashcommand-afk-list.js, Remind/slashcommand-afk.js, Remind/slashcommand-highlight-add.js, Remind/slashcommand-highlight-list.js, Remind/slashcommand-highlight-remove.js, Remind/slashcommand-reminder.js). Generated by scripts/group-commands.js.
const { ChatInputCommandInteraction } = require('discord.js');
const DiscordBot = require('../../client/DiscordBot');
const ApplicationCommand = require('../../structure/ApplicationCommand');
const { t, resolveLocale } = require('../../utils/i18n');
const { PermissionFlagsBits } = require('discord.js');
const { successEmbed, errorEmbed, infoEmbed } = require('../../utils/embeds');

const SUB_PERMS = {
    "tag-create": "32",
    "tag-delete": "32",
    "tag-edit": "32",
};

const handlers = {
    "afk": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const reason = interaction.options.getString('reason') || 'AFK';
        const all = client.database.get('afk-' + interaction.guildId) || {};
        all[interaction.user.id] = { reason, ts: Math.floor(Date.now() / 1000) };
        client.database.set('afk-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('afk.ok', { locale, vars: { reason } }))] });
    },
    "afk-list": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const all = client.database.get('afk-' + interaction.guildId) || {};
        const ids = Object.keys(all);
        if (!ids.length) return interaction.reply({ embeds: [infoEmbed(locale, t('afk.empty', { locale }))], ephemeral: true });
        return interaction.reply({ embeds: [infoEmbed(locale, ids.slice(0, 20).map(id => '<@' + id + '> — ' + all[id].reason).join('\n'))] });
    },
    "highlight-add": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const word = interaction.options.getString('word', true).toLowerCase();
        const all = client.database.get('highlights-' + interaction.guildId) || {};
        const arr = all[interaction.user.id] || [];
        if (!arr.includes(word)) arr.push(word);
        all[interaction.user.id] = arr.slice(0, 25);
        client.database.set('highlights-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('highlight.added', { locale, vars: { word } }))] });
    },
    "highlight-list": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const all = client.database.get('highlights-' + interaction.guildId) || {};
        const arr = all[interaction.user.id] || [];
        if (!arr.length) return interaction.reply({ embeds: [infoEmbed(locale, t('highlight.empty', { locale }))], ephemeral: true });
        return interaction.reply({ embeds: [infoEmbed(locale, arr.join(', '))] });
    },
    "highlight-remove": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const word = interaction.options.getString('word', true).toLowerCase();
        const all = client.database.get('highlights-' + interaction.guildId) || {};
        all[interaction.user.id] = (all[interaction.user.id] || []).filter(w => w !== word);
        client.database.set('highlights-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('highlight.removed', { locale, vars: { word } }))] });
    },
    "reminder": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const minutes = Math.min(10080, Math.max(1, interaction.options.getInteger('minutes', true)));
        const text = interaction.options.getString('text', true);
        require('../../utils/scheduler').scheduleKind(client, interaction.guildId, 'reminder', { userId: interaction.user.id, text }, Date.now() + minutes * 60000);
        return interaction.reply({ embeds: [successEmbed(locale, t('reminder.ok', { locale, vars: { minutes } }))], ephemeral: true });
    },
    "tag-create": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const name = interaction.options.getString('name', true);
        const content = interaction.options.getString('content', true);
        const all = client.database.get('tags-' + interaction.guildId) || {};
        all[name] = content;
        client.database.set('tags-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('tag.saved', { locale, vars: { name } }))] });
    },
    "tag-delete": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const name = interaction.options.getString('name', true);
        const all = client.database.get('tags-' + interaction.guildId) || {};
        if (!all[name]) return interaction.reply({ embeds: [errorEmbed(locale, t('tag.notfound', { locale }))], ephemeral: true });
        delete all[name];
        client.database.set('tags-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('tag.deleted', { locale, vars: { name } }))] });
    },
    "tag-edit": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const name = interaction.options.getString('name', true);
        const content = interaction.options.getString('content', true);
        const all = client.database.get('tags-' + interaction.guildId) || {};
        all[name] = content;
        client.database.set('tags-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('tag.saved', { locale, vars: { name } }))] });
    },
    "tag-info": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const name = interaction.options.getString('name', true);
        const all = client.database.get('tags-' + interaction.guildId) || {};
        if (!all[name]) return interaction.reply({ embeds: [errorEmbed(locale, t('tag.notfound', { locale }))], ephemeral: true });
        return interaction.reply({ embeds: [infoEmbed(locale, all[name].slice(0, 3500))] });
    },
    "tag-list": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const all = client.database.get('tags-' + interaction.guildId) || {};
        const keys = Object.keys(all);
        if (!keys.length) return interaction.reply({ embeds: [infoEmbed(locale, t('tag.empty', { locale }))], ephemeral: true });
        return interaction.reply({ embeds: [infoEmbed(locale, keys.slice(0, 30).join(', '))] });
    },
};

module.exports = new ApplicationCommand({
    command: {
        name: "tags", description: "🏷️ Tags, reminders, AFK and highlights.", type: 1,
        description_localizations: { 'pt-BR': "🏷️ Tags, lembretes, AFK e destaques." },
        options: [
            {
                name: "afk",
                description: "💤 Sets your AFK status.",
                description_localizations: {"pt-BR":"💤 Define seu status AFK."},
                type: 1,
                options: [{"name":"reason","name_localizations":{"pt-BR":"motivo"},"description":"Reason","description_localizations":{"pt-BR":"Motivo"},"type":3}],
            },
            {
                name: "afk-list",
                description: "💤 Lists AFK members.",
                description_localizations: {"pt-BR":"💤 Lista membros AFK."},
                type: 1,
                options: [],
            },
            {
                name: "highlight-add",
                description: "🔔 Adds a highlight word.",
                description_localizations: {"pt-BR":"🔔 Adiciona palavra de destaque."},
                type: 1,
                options: [{"name":"word","description":"Word","description_localizations":{"pt-BR":"Palavra"},"type":3,"required":true}],
            },
            {
                name: "highlight-list",
                description: "🔔 Lists your highlight words.",
                description_localizations: {"pt-BR":"🔔 Lista suas palavras de destaque."},
                type: 1,
                options: [],
            },
            {
                name: "highlight-remove",
                description: "🔔 Removes a highlight word.",
                description_localizations: {"pt-BR":"🔔 Remove palavra de destaque."},
                type: 1,
                options: [{"name":"word","description":"Word","description_localizations":{"pt-BR":"Palavra"},"type":3,"required":true}],
            },
            {
                name: "reminder",
                description: "⏰ Reminds you via DM after minutes.",
                description_localizations: {"pt-BR":"⏰ Lembra você via DM após minutos."},
                type: 1,
                options: [{"name":"minutes","name_localizations":{"pt-BR":"minutos"},"description":"Minutes","description_localizations":{"pt-BR":"Minutos"},"type":4,"required":true},{"name":"text","name_localizations":{"pt-BR":"texto"},"description":"Reminder","description_localizations":{"pt-BR":"Lembrete"},"type":3,"required":true}],
            },
            {
                name: "tag-create",
                description: "🏷️ Creates a tag.",
                description_localizations: {"pt-BR":"🏷️ Cria uma tag."},
                type: 1,
                options: [{"name":"name","description":"Tag name","description_localizations":{"pt-BR":"Nome da tag"},"type":3,"required":true},{"name":"content","name_localizations":{"pt-BR":"conteudo"},"description":"Content","description_localizations":{"pt-BR":"Conteúdo"},"type":3,"required":true}],
            },
            {
                name: "tag-delete",
                description: "🏷️ Deletes a tag.",
                description_localizations: {"pt-BR":"🏷️ Apaga uma tag."},
                type: 1,
                options: [{"name":"name","description":"Tag name","description_localizations":{"pt-BR":"Nome da tag"},"type":3,"required":true}],
            },
            {
                name: "tag-edit",
                description: "🏷️ Edits a tag.",
                description_localizations: {"pt-BR":"🏷️ Edita uma tag."},
                type: 1,
                options: [{"name":"name","description":"Tag name","description_localizations":{"pt-BR":"Nome da tag"},"type":3,"required":true},{"name":"content","name_localizations":{"pt-BR":"conteudo"},"description":"Content","description_localizations":{"pt-BR":"Conteúdo"},"type":3,"required":true}],
            },
            {
                name: "tag-info",
                description: "🏷️ Shows a tag.",
                description_localizations: {"pt-BR":"🏷️ Mostra uma tag."},
                type: 1,
                options: [{"name":"name","description":"Tag name","description_localizations":{"pt-BR":"Nome da tag"},"type":3,"required":true}],
            },
            {
                name: "tag-list",
                description: "🏷️ Lists tags.",
                description_localizations: {"pt-BR":"🏷️ Lista tags."},
                type: 1,
                options: [],
            },
        ],
    },
    /**
     * @param {DiscordBot} client
     * @param {ChatInputCommandInteraction} interaction
     */
    run: async (client, interaction) => {
        const sub = interaction.options.getSubcommand();
        const need = SUB_PERMS[sub];
        if (need) {
            let ok = false;
            try { ok = !!interaction.memberPermissions && interaction.memberPermissions.has(BigInt(need)); } catch { ok = false; }
            if (!ok) {
                const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
                return interaction.reply({ content: t('handler.missing_permissions', { locale }), ephemeral: true });
            }
        }
        const fn = handlers[sub];
        if (!fn) {
            return interaction.reply({ content: 'Unknown subcommand: ' + sub, ephemeral: true });
        }
        return fn(client, interaction);
    },
}).toJSON();
