// Grouped from 23 flat commands (Fun/slashcommand-8ball.js, Fun/slashcommand-cat.js, Fun/slashcommand-coinflip.js, Fun/slashcommand-compliment.js, Fun/slashcommand-dadjoke.js, Fun/slashcommand-dare.js, Fun/slashcommand-dog.js, Fun/slashcommand-fact.js, Fun/slashcommand-fox.js, Fun/slashcommand-joke.js, Fun/slashcommand-meme.js, Fun/slashcommand-mock.js, Fun/slashcommand-neverhaveiever.js, Fun/slashcommand-pick.js, Fun/slashcommand-quote.js, Fun/slashcommand-reverse.js, Fun/slashcommand-roll.js, Fun/slashcommand-rps.js, Fun/slashcommand-ship.js, Fun/slashcommand-trivia.js, Fun/slashcommand-truth.js, Fun/slashcommand-vaporwave.js, Fun/slashcommand-wouldyourather.js). Generated by scripts/group-commands.js.
const { ChatInputCommandInteraction } = require('discord.js');
const DiscordBot = require('../../client/DiscordBot');
const ApplicationCommand = require('../../structure/ApplicationCommand');
const { t, resolveLocale } = require('../../utils/i18n');
const { successEmbed, errorEmbed, infoEmbed } = require('../../utils/embeds');

const SUB_PERMS = {
};

const handlers = {
    "8ball": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const q = interaction.options.getString('question', true);
        const answers = t('eightball.answers', { locale }).split('|');
        return interaction.reply({ embeds: [infoEmbed(locale, '**' + q + '**\n' + answers[Math.floor(Math.random() * answers.length)])] });
    },
    "cat": async (client, interaction) => {
        await interaction.deferReply();
        try {
            const r = await fetch('https://cataas.com/cat?json=true');
            let img = null;
            if ('cat' === 'cat') { const j = await r.json().catch(() => null); img = 'https://cataas.com/cat?x=' + Date.now(); }
            else if ('cat' === 'dog') { const j = await r.json(); img = j.message; }
            else if ('cat' === 'fox') { const j = await r.json(); img = j.image; }
            else if ('cat' === 'meme') { const j = await r.json(); img = j.url; }
            const { EmbedBuilder } = require('discord.js');
            return interaction.editReply({ embeds: [new EmbedBuilder().setColor(0xffffff).setImage(img)] });
        } catch (e) { const locale2 = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale }); return interaction.editReply({ embeds: [errorEmbed(locale2, t('mod_error', { locale: locale2, vars: { error: e.message || e } }))] }); }
    },
    "coinflip": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const side = Math.random() < 0.5 ? t('coinflip.heads', { locale }) : t('coinflip.tails', { locale });
        return interaction.reply({ embeds: [infoEmbed(locale, '**' + side + '**')] });
    },
    "compliment": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const arr = t('compliment.item', { locale }).split('|');
        return interaction.reply({ embeds: [infoEmbed(locale, arr[Math.floor(Math.random() * arr.length)])] });
    },
    "dadjoke": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        await interaction.deferReply();
        try {
            const r = await fetch('https://icanhazdadjoke.com/', { headers: { Accept: 'application/json' } });
            const j = await r.json();
            return interaction.editReply({ embeds: [infoEmbed(locale, j.joke)] });
        } catch (e) { return interaction.editReply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))] }); }
    },
    "dare": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const arr = t('dare.item', { locale }).split('|');
        return interaction.reply({ embeds: [infoEmbed(locale, arr[Math.floor(Math.random() * arr.length)])] });
    },
    "dog": async (client, interaction) => {
        await interaction.deferReply();
        try {
            const r = await fetch('https://dog.ceo/api/breeds/image/random');
            let img = null;
            if ('dog' === 'cat') { const j = await r.json().catch(() => null); img = 'https://cataas.com/cat?x=' + Date.now(); }
            else if ('dog' === 'dog') { const j = await r.json(); img = j.message; }
            else if ('dog' === 'fox') { const j = await r.json(); img = j.image; }
            else if ('dog' === 'meme') { const j = await r.json(); img = j.url; }
            const { EmbedBuilder } = require('discord.js');
            return interaction.editReply({ embeds: [new EmbedBuilder().setColor(0xffffff).setImage(img)] });
        } catch (e) { const locale2 = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale }); return interaction.editReply({ embeds: [errorEmbed(locale2, t('mod_error', { locale: locale2, vars: { error: e.message || e } }))] }); }
    },
    "fact": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const arr = t('fact.item', { locale }).split('|');
        return interaction.reply({ embeds: [infoEmbed(locale, arr[Math.floor(Math.random() * arr.length)])] });
    },
    "fox": async (client, interaction) => {
        await interaction.deferReply();
        try {
            const r = await fetch('https://randomfox.ca/floof/');
            let img = null;
            if ('fox' === 'cat') { const j = await r.json().catch(() => null); img = 'https://cataas.com/cat?x=' + Date.now(); }
            else if ('fox' === 'dog') { const j = await r.json(); img = j.message; }
            else if ('fox' === 'fox') { const j = await r.json(); img = j.image; }
            else if ('fox' === 'meme') { const j = await r.json(); img = j.url; }
            const { EmbedBuilder } = require('discord.js');
            return interaction.editReply({ embeds: [new EmbedBuilder().setColor(0xffffff).setImage(img)] });
        } catch (e) { const locale2 = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale }); return interaction.editReply({ embeds: [errorEmbed(locale2, t('mod_error', { locale: locale2, vars: { error: e.message || e } }))] }); }
    },
    "joke": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        await interaction.deferReply();
        try {
            const j = await (await fetch('https://official-joke-api.appspot.com/random_joke')).json();
            return interaction.editReply({ embeds: [infoEmbed(locale, '**' + j.setup + '**\n' + j.punchline)] });
        } catch (e) { return interaction.editReply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))] }); }
    },
    "meme": async (client, interaction) => {
        await interaction.deferReply();
        try {
            const r = await fetch('https://meme-api.com/gimme');
            let img = null;
            if ('meme' === 'cat') { const j = await r.json().catch(() => null); img = 'https://cataas.com/cat?x=' + Date.now(); }
            else if ('meme' === 'dog') { const j = await r.json(); img = j.message; }
            else if ('meme' === 'fox') { const j = await r.json(); img = j.image; }
            else if ('meme' === 'meme') { const j = await r.json(); img = j.url; }
            const { EmbedBuilder } = require('discord.js');
            return interaction.editReply({ embeds: [new EmbedBuilder().setColor(0xffffff).setImage(img)] });
        } catch (e) { const locale2 = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale }); return interaction.editReply({ embeds: [errorEmbed(locale2, t('mod_error', { locale: locale2, vars: { error: e.message || e } }))] }); }
    },
    "mock": async (client, interaction) => {
        const text = interaction.options.getString('text', true);
        return interaction.reply({ content: [...text.toLowerCase()].map((c, i) => (i % 2 ? c.toUpperCase() : c)).join('').slice(0, 1900) });
    },
    "neverhaveiever": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const arr = t('neverhaveiever.item', { locale }).split('|');
        return interaction.reply({ embeds: [infoEmbed(locale, arr[Math.floor(Math.random() * arr.length)])] });
    },
    "pick": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const opts = interaction.options.getString('options', true).split(',').map(s => s.trim()).filter(Boolean);
        if (!opts.length) return interaction.reply({ embeds: [errorEmbed(locale, t('pick.empty', { locale }))], ephemeral: true });
        return interaction.reply({ embeds: [infoEmbed(locale, '**' + opts[Math.floor(Math.random() * opts.length)] + '**')] });
    },
    "quote": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const arr = t('quote.item', { locale }).split('|');
        return interaction.reply({ embeds: [infoEmbed(locale, arr[Math.floor(Math.random() * arr.length)])] });
    },
    "reverse": async (client, interaction) => {
        const text = interaction.options.getString('text', true);
        return interaction.reply({ content: [...text].reverse().join('').slice(0, 1900) });
    },
    "roll": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const sides = Math.min(1000, Math.max(2, interaction.options.getInteger('sides') || 6));
        const v = 1 + Math.floor(Math.random() * sides);
        return interaction.reply({ embeds: [infoEmbed(locale, t('roll.body', { locale, vars: { v, sides } }))] });
    },
    "rps": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const u = interaction.options.getString('choice', true);
        const b = ['rock', 'paper', 'scissors'][Math.floor(Math.random() * 3)];
        const win = (u === 'rock' && b === 'scissors') || (u === 'paper' && b === 'rock') || (u === 'scissors' && b === 'paper');
        const res = u === b ? t('rps.tie', { locale }) : win ? t('rps.win', { locale }) : t('rps.lose', { locale });
        return interaction.reply({ embeds: [infoEmbed(locale, t('rps.body', { locale, vars: { u, b, res } }))] });
    },
    "ship": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const a = interaction.options.getUser('a', true);
        const b = interaction.options.getUser('b') || interaction.user;
        const pct = Math.floor(Math.random() * 101);
        return interaction.reply({ embeds: [infoEmbed(locale, t('ship.body', { locale, vars: { a: a.username, b: b.username, pct } }))] });
    },
    "trivia": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        await interaction.deferReply();
        try {
            const j = await (await fetch('https://opentdb.com/api.php?amount=1&type=multiple')).json();
            const q = j.results?.[0];
            if (!q) throw new Error('no question');
            const de = s => s.replace(/&quot;/g, '"').replace(/&#039;/g, "'").replace(/&amp;/g, '&');
            return interaction.editReply({ embeds: [infoEmbed(locale, '**' + de(q.question) + '**\n||' + de(q.correct_answer) + '||')] });
        } catch (e) { return interaction.editReply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))] }); }
    },
    "truth": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const arr = t('truth.item', { locale }).split('|');
        return interaction.reply({ embeds: [infoEmbed(locale, arr[Math.floor(Math.random() * arr.length)])] });
    },
    "vaporwave": async (client, interaction) => {
        const text = interaction.options.getString('text', true);
        const out = [...text].map(c => (c >= '!' && c <= '~' ? String.fromCharCode(c.charCodeAt(0) + 0xFEE0) : c === ' ' ? '　' : c)).join('').slice(0, 1500);
        return interaction.reply({ content: out });
    },
    "wouldyourather": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const arr = t('wouldyourather.item', { locale }).split('|');
        return interaction.reply({ embeds: [infoEmbed(locale, arr[Math.floor(Math.random() * arr.length)])] });
    },
};

module.exports = new ApplicationCommand({
    command: {
        name: "fun", description: "🎮 Fun commands.", type: 1,
        description_localizations: { 'pt-BR': "🎮 Comandos divertidos." },
        options: [
            {
                name: "8ball",
                description: "🎱 Ask the magic 8-ball.",
                description_localizations: {"pt-BR":"🎱 Pergunte ao globo mágico."},
                type: 1,
                options: [{"name":"question","name_localizations":{"pt-BR":"pergunta"},"description":"Question","description_localizations":{"pt-BR":"Pergunta"},"type":3,"required":true}],
            },
            {
                name: "cat",
                description: "🐱 Random cat image.",
                description_localizations: {"pt-BR":"🐱 Imagem aleatória de gato."},
                type: 1,
                options: [],
            },
            {
                name: "coinflip",
                description: "🪙 Flip a coin.",
                description_localizations: {"pt-BR":"🪙 Joga uma moeda."},
                type: 1,
                options: [],
            },
            {
                name: "compliment",
                description: "💛 Random compliment.",
                description_localizations: {"pt-BR":"💛 Elogio aleatório."},
                type: 1,
                options: [],
            },
            {
                name: "dadjoke",
                description: "👨 Random dad joke.",
                description_localizations: {"pt-BR":"👨 Piada de pai aleatória."},
                type: 1,
                options: [],
            },
            {
                name: "dare",
                description: "😈 Dare challenge.",
                description_localizations: {"pt-BR":"😈 Desafio de ousadia."},
                type: 1,
                options: [],
            },
            {
                name: "dog",
                description: "🐶 Random dog image.",
                description_localizations: {"pt-BR":"🐶 Imagem aleatória de cachorro."},
                type: 1,
                options: [],
            },
            {
                name: "fact",
                description: "🧠 Random fact (local list).",
                description_localizations: {"pt-BR":"🧠 Curiosidade aleatória (lista local)."},
                type: 1,
                options: [],
            },
            {
                name: "fox",
                description: "🦊 Random fox image.",
                description_localizations: {"pt-BR":"🦊 Imagem aleatória de raposa."},
                type: 1,
                options: [],
            },
            {
                name: "joke",
                description: "😂 Random joke.",
                description_localizations: {"pt-BR":"😂 Piada aleatória."},
                type: 1,
                options: [],
            },
            {
                name: "meme",
                description: "😂 Random meme.",
                description_localizations: {"pt-BR":"😂 Meme aleatório."},
                type: 1,
                options: [],
            },
            {
                name: "mock",
                description: "🙃 mOcKs text.",
                description_localizations: {"pt-BR":"🙃 TrAnSfOrMa texto em mOcK."},
                type: 1,
                options: [{"name":"text","name_localizations":{"pt-BR":"texto"},"description":"Text","description_localizations":{"pt-BR":"Texto"},"type":3,"required":true}],
            },
            {
                name: "neverhaveiever",
                description: "🍺 Never have I ever.",
                description_localizations: {"pt-BR":"🍺 Eu nunca."},
                type: 1,
                options: [],
            },
            {
                name: "pick",
                description: "🎯 Pick one of the options (comma separated).",
                description_localizations: {"pt-BR":"🎯 Escolhe uma das opções (separadas por vírgula)."},
                type: 1,
                options: [{"name":"options","name_localizations":{"pt-BR":"opcoes"},"description":"a, b, c","description_localizations":{"pt-BR":"a, b, c"},"type":3,"required":true}],
            },
            {
                name: "quote",
                description: "💬 Random quote (local list).",
                description_localizations: {"pt-BR":"💬 Frase aleatória (lista local)."},
                type: 1,
                options: [],
            },
            {
                name: "reverse",
                description: "🔄 Reverses text.",
                description_localizations: {"pt-BR":"🔄 Inverte texto."},
                type: 1,
                options: [{"name":"text","name_localizations":{"pt-BR":"texto"},"description":"Text","description_localizations":{"pt-BR":"Texto"},"type":3,"required":true}],
            },
            {
                name: "roll",
                description: "🎲 Roll a dice (default d6).",
                description_localizations: {"pt-BR":"🎲 Rola um dado (padrão d6)."},
                type: 1,
                options: [{"name":"sides","name_localizations":{"pt-BR":"lados"},"description":"Sides","description_localizations":{"pt-BR":"Lados"},"type":4}],
            },
            {
                name: "rps",
                description: "✂️ Rock paper scissors.",
                description_localizations: {"pt-BR":"✂️ Pedra papel tesoura."},
                type: 1,
                options: [{"name":"choice","name_localizations":{"pt-BR":"escolha"},"description":"rock/paper/scissors","description_localizations":{"pt-BR":"pedra/papel/tesoura"},"type":3,"required":true,"choices":[{"name":"rock","value":"rock"},{"name":"paper","value":"paper"},{"name":"scissors","value":"scissors"}]}],
            },
            {
                name: "ship",
                description: "💘 Ship two members.",
                description_localizations: {"pt-BR":"💘 Shippa dois membros."},
                type: 1,
                options: [{"name":"a","description":"First","description_localizations":{"pt-BR":"Primeiro"},"type":6,"required":true},{"name":"b","description":"Second","description_localizations":{"pt-BR":"Segundo"},"type":6}],
            },
            {
                name: "trivia",
                description: "❓ Random trivia (answer in spoiler).",
                description_localizations: {"pt-BR":"❓ Trivia aleatória (resposta em spoiler)."},
                type: 1,
                options: [],
            },
            {
                name: "truth",
                description: "🙊 Truth question.",
                description_localizations: {"pt-BR":"🙊 Pergunta de verdade."},
                type: 1,
                options: [],
            },
            {
                name: "vaporwave",
                description: "🌊 Ｖａｐｏｒｗａｖｅ text.",
                description_localizations: {"pt-BR":"🌊 Texto ｖａｐｏｒｗａｖｅ."},
                type: 1,
                options: [{"name":"text","name_localizations":{"pt-BR":"texto"},"description":"Text","description_localizations":{"pt-BR":"Texto"},"type":3,"required":true}],
            },
            {
                name: "wouldyourather",
                description: "🤔 Would you rather.",
                description_localizations: {"pt-BR":"🤔 Você prefere."},
                type: 1,
                options: [],
            },
        ],
    },
    /**
     * @param {DiscordBot} client
     * @param {ChatInputCommandInteraction} interaction
     */
    run: async (client, interaction) => {
        const sub = interaction.options.getSubcommand();
        const need = SUB_PERMS[sub];
        if (need) {
            let ok = false;
            try { ok = !!interaction.memberPermissions && interaction.memberPermissions.has(BigInt(need)); } catch { ok = false; }
            if (!ok) {
                const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
                return interaction.reply({ content: t('handler.missing_permissions', { locale }), ephemeral: true });
            }
        }
        const fn = handlers[sub];
        if (!fn) {
            return interaction.reply({ content: 'Unknown subcommand: ' + sub, ephemeral: true });
        }
        return fn(client, interaction);
    },
}).toJSON();
