// Grouped from 24 flat commands (Utility/slashcommand-avatar.js, Utility/slashcommand-banner.js, Utility/slashcommand-botinfo.js, Utility/slashcommand-calc.js, Utility/slashcommand-channels.js, Utility/slashcommand-color-info.js, Utility/slashcommand-dictionary.js, Utility/slashcommand-emoji-info.js, Utility/slashcommand-invite-info.js, Utility/slashcommand-invite.js, Utility/slashcommand-member.js, Utility/slashcommand-membercount.js, Utility/slashcommand-password.js, Utility/slashcommand-privacy.js, Utility/slashcommand-qrcode.js, Utility/slashcommand-roles.js, Utility/slashcommand-serverinfo.js, Utility/slashcommand-support.js, Utility/slashcommand-time.js, Utility/slashcommand-timestamp.js, Utility/slashcommand-translate.js, Utility/slashcommand-uptime.js, Utility/slashcommand-vote.js, Utility/slashcommand-weather.js). Generated by scripts/group-commands.js.
const { ChatInputCommandInteraction } = require('discord.js');
const DiscordBot = require('../../client/DiscordBot');
const ApplicationCommand = require('../../structure/ApplicationCommand');
const { t, resolveLocale } = require('../../utils/i18n');
const { successEmbed, errorEmbed, infoEmbed } = require('../../utils/embeds');

const SUB_PERMS = {
};

const handlers = {
    "avatar": async (client, interaction) => {
        const user = interaction.options.getUser('user') || interaction.user;
        const url = user.displayAvatarURL({ size: 1024 });
        const { EmbedBuilder } = require('discord.js');
        return interaction.reply({ embeds: [new EmbedBuilder().setColor(0xffffff).setImage(url).setTitle(user.tag)] });
    },
    "banner": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user') || interaction.user;
        const full = await user.fetch().catch(() => user);
        const url = full.bannerURL ? full.bannerURL({ size: 1024 }) : null;
        if (!url) return interaction.reply({ embeds: [infoEmbed(locale, t('banner.none', { locale }))], ephemeral: true });
        const { EmbedBuilder } = require('discord.js');
        return interaction.reply({ embeds: [new EmbedBuilder().setColor(0xffffff).setImage(url).setTitle(full.tag)] });
    },
    "botinfo": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const desc = t('botinfo.body', { locale, vars: { guilds: client.guilds.cache.size, ping: client.ws.ping, uptime: Math.floor((Date.now() - (client.readyTimestamp || Date.now())) / 1000) } });
        return interaction.reply({ embeds: [infoEmbed(locale, desc)] });
    },
    "calc": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const expr = interaction.options.getString('expr', true);
        if (!/^[0-9+\-*/().\s%^]+$/.test(expr)) return interaction.reply({ embeds: [errorEmbed(locale, t('calc.invalid', { locale }))], ephemeral: true });
        try {
            const val = Function('"use strict";return(' + expr.replace(/\^/g, '**') + ')')();
            if (typeof val !== 'number' || !isFinite(val)) throw new Error('bad result');
            return interaction.reply({ embeds: [infoEmbed(locale, t('calc.body', { locale, vars: { expr, val } }))] });
        } catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
    "channels": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const list = interaction.guild.channels.cache.sort((a, b) => a.position - b.position).first(30).map(c => c.toString()).join(' ');
        return interaction.reply({ embeds: [infoEmbed(locale, list.slice(0, 3500) || t('roles.empty', { locale }))] });
    },
    "color-info": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        let hex = interaction.options.getString('hex', true).replace('#', '');
        if (!/^[0-9a-fA-F]{6}$/.test(hex)) return interaction.reply({ embeds: [errorEmbed(locale, t('color.invalid', { locale }))], ephemeral: true });
        const r = parseInt(hex.slice(0, 2), 16), g = parseInt(hex.slice(2, 4), 16), b = parseInt(hex.slice(4, 6), 16);
        const { EmbedBuilder } = require('discord.js');
        return interaction.reply({ embeds: [new EmbedBuilder().setColor(parseInt(hex, 16)).setTitle('#' + hex).setDescription(t('color.body', { locale, vars: { r, g, b } }))] });
    },
    "dictionary": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        await interaction.deferReply();
        const word = interaction.options.getString('word', true);
        try {
            const r = await fetch('https://api.dictionaryapi.dev/api/v2/entries/en/' + encodeURIComponent(word));
            if (!r.ok) throw new Error('not found');
            const j = await r.json();
            const def = j?.[0]?.meanings?.[0]?.definitions?.[0]?.definition || '?';
            return interaction.editReply({ embeds: [infoEmbed(locale, t('dict.body', { locale, vars: { word, def } }))] });
        } catch (e) { return interaction.editReply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))] }); }
    },
    "emoji-info": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const raw = interaction.options.getString('emoji', true);
        const m = raw.match(/<(a)?:(\w+):(\d+)>/);
        if (!m) return interaction.reply({ embeds: [errorEmbed(locale, t('emojiinfo.invalid', { locale }))], ephemeral: true });
        const e = await interaction.guild.emojis.fetch(m[3]).catch(() => null);
        const url = 'https://cdn.discordapp.com/emojis/' + m[3] + (m[1] ? '.gif' : '.png');
        const { EmbedBuilder } = require('discord.js');
        return interaction.reply({ embeds: [new EmbedBuilder().setColor(0xffffff).setTitle(m[2]).setDescription((e ? t('emojiinfo.guild', { locale, vars: { name: e.guild.name } }) : '') + '\n' + url).setImage(url)] });
    },
    "invite": async (client, interaction) => {
        const url = 'https://discord.com/oauth2/authorize?client_id=' + client.user.id + '&permissions=8&scope=bot%20applications.commands';
        return interaction.reply({ content: url, ephemeral: true });
    },
    "invite-info": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const raw = interaction.options.getString('code', true).split('/').pop();
        try {
            const inv = await client.fetchInvite(raw, { withCounts: true });
            return interaction.reply({ embeds: [infoEmbed(locale, t('inviteinfo.body', { locale, vars: { guild: inv.guild?.name || '?', channel: inv.channel?.name || '?', members: inv.memberCount ?? '?', online: inv.presenceCount ?? '?' } }))] });
        } catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
    "member": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user') || interaction.user;
        const m = await interaction.guild.members.fetch(user.id).catch(() => null);
        const desc = t('member.body', { locale, vars: { tag: user.tag, id: user.id, joined: m ? Math.floor(m.joinedTimestamp / 1000) : 0, created: Math.floor(user.createdTimestamp / 1000) } });
        return interaction.reply({ embeds: [infoEmbed(locale, desc)] });
    },
    "membercount": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const g = interaction.guild;
        const total = g.memberCount;
        return interaction.reply({ embeds: [infoEmbed(locale, t('membercount.body', { locale, vars: { total } }))] });
    },
    "password": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const len = Math.min(64, Math.max(4, interaction.options.getInteger('length') || 12));
        const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*';
        let out = '';
        require('crypto').randomFillSync(new Uint32Array(len));
        const rnd = require('crypto').randomBytes(len);
        for (let i = 0; i < len; i++) out += chars[rnd[i] % chars.length];
        return interaction.reply({ content: '**' + out + '**', ephemeral: true });
    },
    "privacy": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        return interaction.reply({ embeds: [infoEmbed(locale, t('privacy.body', { locale }))] });
    },
    "qrcode": async (client, interaction) => {
        const text = interaction.options.getString('text', true);
        const url = 'https://api.qrserver.com/v1/create-qr-code/?size=256x256&data=' + encodeURIComponent(text);
        const { EmbedBuilder } = require('discord.js');
        return interaction.reply({ embeds: [new EmbedBuilder().setColor(0xffffff).setImage(url).setTitle(text.slice(0, 100))] });
    },
    "roles": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const roles = interaction.guild.roles.cache.sort((a, b) => b.position - a.position).first(30).map(r => r.toString()).join(' ');
        return interaction.reply({ embeds: [infoEmbed(locale, roles.slice(0, 3500) || t('roles.empty', { locale }))] });
    },
    "serverinfo": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const g = interaction.guild;
        const desc = t('serverinfo.body', { locale, vars: { name: g.name, id: g.id, members: g.memberCount, created: Math.floor(g.createdTimestamp / 1000), owner: (await g.fetchOwner().catch(() => null))?.user.tag || '?' } });
        return interaction.reply({ embeds: [infoEmbed(locale, desc)] });
    },
    "support": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        return interaction.reply({ embeds: [infoEmbed(locale, t('support.body', { locale }))] });
    },
    "time": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        await interaction.deferReply();
        const zone = interaction.options.getString('zone', true);
        try {
            const r = await fetch('https://worldtimeapi.org/api/timezone/' + encodeURIComponent(zone));
            if (!r.ok) throw new Error('invalid timezone');
            const j = await r.json();
            return interaction.editReply({ embeds: [infoEmbed(locale, t('time.body', { locale, vars: { zone, dt: j.datetime } }))] });
        } catch (e) { return interaction.editReply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))] }); }
    },
    "timestamp": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const raw = interaction.options.getString('date', true);
        const ms = Date.parse(raw.replace(' ', 'T') + 'Z');
        if (isNaN(ms)) return interaction.reply({ embeds: [errorEmbed(locale, t('timestamp.invalid', { locale }))], ephemeral: true });
        const s = Math.floor(ms / 1000);
        return interaction.reply({ content: '<t:' + s + ':F>  (<t:' + s + ':R>)', ephemeral: false });
    },
    "translate": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        await interaction.deferReply();
        const text = interaction.options.getString('text', true);
        const to = interaction.options.getString('to', true);
        try {
            const j = await (await fetch('https://api.mymemory.translated.net/get?q=' + encodeURIComponent(text) + '&langpair=autodetect|' + encodeURIComponent(to))).json();
            const out = j?.responseData?.translatedText || '?';
            return interaction.editReply({ embeds: [infoEmbed(locale, out)] });
        } catch (e) { return interaction.editReply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))] }); }
    },
    "uptime": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const s = Math.floor((Date.now() - (client.readyTimestamp || Date.now())) / 1000);
        const h = Math.floor(s / 3600), m = Math.floor((s % 3600) / 60), ss = s % 60;
        return interaction.reply({ embeds: [infoEmbed(locale, t('uptime.body', { locale, vars: { h, m, ss } }))] });
    },
    "vote": async (client, interaction) => {
        const topic = interaction.options.getString('topic', true);
        const msg = await interaction.reply({ content: '**' + topic + '**', fetchReply: true });
        try { await msg.react('✅'); await msg.react('❌'); } catch {}
        return undefined;
    },
    "weather": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        await interaction.deferReply();
        const city = interaction.options.getString('city', true);
        try {
            const r = await fetch('https://wttr.in/' + encodeURIComponent(city) + '?format=j1');
            const j = await r.json();
            const c = j.current_condition?.[0];
            if (!c) throw new Error('no data');
            return interaction.editReply({ embeds: [infoEmbed(locale, t('weather.body', { locale, vars: { city, temp: c.temp_C, desc: c.weatherDesc?.[0]?.value || '', hum: c.humidity } }))] });
        } catch (e) { return interaction.editReply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))] }); }
    },
};

module.exports = new ApplicationCommand({
    command: {
        name: "utility", description: "🧰 Utility tools.", type: 1,
        description_localizations: { 'pt-BR': "🧰 Ferramentas utilitárias." },
        options: [
            {
                name: "avatar",
                description: "ℹ️ Shows a user avatar.",
                description_localizations: {"pt-BR":"ℹ️ Mostra o avatar de um usuário."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"User","description_localizations":{"pt-BR":"Usuário"},"type":6}],
            },
            {
                name: "banner",
                description: "ℹ️ Shows a user banner.",
                description_localizations: {"pt-BR":"ℹ️ Mostra o banner de um usuário."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"User","description_localizations":{"pt-BR":"Usuário"},"type":6}],
            },
            {
                name: "botinfo",
                description: "ℹ️ Shows bot information.",
                description_localizations: {"pt-BR":"ℹ️ Mostra informações do bot."},
                type: 1,
                options: [],
            },
            {
                name: "calc",
                description: "🔢 Evaluates a math expression safely.",
                description_localizations: {"pt-BR":"🔢 Calcula expressão matemática com segurança."},
                type: 1,
                options: [{"name":"expr","name_localizations":{"pt-BR":"expressao"},"description":"ex: (2+3)*4","description_localizations":{"pt-BR":"ex: (2+3)*4"},"type":3,"required":true}],
            },
            {
                name: "channels",
                description: "ℹ️ Lists server channels.",
                description_localizations: {"pt-BR":"ℹ️ Lista canais do servidor."},
                type: 1,
                options: [],
            },
            {
                name: "color-info",
                description: "🎨 Shows hex color info.",
                description_localizations: {"pt-BR":"🎨 Mostra info de cor hex."},
                type: 1,
                options: [{"name":"hex","description":"#ff0000","description_localizations":{"pt-BR":"#ff0000"},"type":3,"required":true}],
            },
            {
                name: "dictionary",
                description: "📖 Defines an English word.",
                description_localizations: {"pt-BR":"📖 Define palavra em inglês."},
                type: 1,
                options: [{"name":"word","description":"Word","description_localizations":{"pt-BR":"Palavra"},"type":3,"required":true}],
            },
            {
                name: "emoji-info",
                description: "ℹ️ Shows emoji information.",
                description_localizations: {"pt-BR":"ℹ️ Mostra informações de um emoji."},
                type: 1,
                options: [{"name":"emoji","description":"Emoji","description_localizations":{"pt-BR":"Emoji"},"type":3,"required":true}],
            },
            {
                name: "invite",
                description: "ℹ️ Gets the bot invite link.",
                description_localizations: {"pt-BR":"ℹ️ Pega o link de convite do bot."},
                type: 1,
                options: [],
            },
            {
                name: "invite-info",
                description: "ℹ️ Shows invite information.",
                description_localizations: {"pt-BR":"ℹ️ Mostra informações de um convite."},
                type: 1,
                options: [{"name":"code","name_localizations":{"pt-BR":"codigo"},"description":"Invite code or URL","description_localizations":{"pt-BR":"Código ou URL do convite"},"type":3,"required":true}],
            },
            {
                name: "member",
                description: "ℹ️ Shows member information.",
                description_localizations: {"pt-BR":"ℹ️ Mostra informações de um membro."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Member","description_localizations":{"pt-BR":"Membro"},"type":6}],
            },
            {
                name: "membercount",
                description: "ℹ️ Shows member count.",
                description_localizations: {"pt-BR":"ℹ️ Mostra contagem de membros."},
                type: 1,
                options: [],
            },
            {
                name: "password",
                description: "🔑 Generates a random password.",
                description_localizations: {"pt-BR":"🔑 Gera uma senha aleatória."},
                type: 1,
                options: [{"name":"length","name_localizations":{"pt-BR":"tamanho"},"description":"4-64","description_localizations":{"pt-BR":"4-64"},"type":4}],
            },
            {
                name: "privacy",
                description: "ℹ️ Shows privacy info.",
                description_localizations: {"pt-BR":"ℹ️ Mostra info de privacidade."},
                type: 1,
                options: [],
            },
            {
                name: "qrcode",
                description: "🔳 Generates a QR code image.",
                description_localizations: {"pt-BR":"🔳 Gera imagem de QR code."},
                type: 1,
                options: [{"name":"text","name_localizations":{"pt-BR":"texto"},"description":"Text or URL","description_localizations":{"pt-BR":"Texto ou URL"},"type":3,"required":true}],
            },
            {
                name: "roles",
                description: "ℹ️ Lists server roles.",
                description_localizations: {"pt-BR":"ℹ️ Lista cargos do servidor."},
                type: 1,
                options: [],
            },
            {
                name: "serverinfo",
                description: "ℹ️ Shows server information.",
                description_localizations: {"pt-BR":"ℹ️ Mostra informações do servidor."},
                type: 1,
                options: [],
            },
            {
                name: "support",
                description: "ℹ️ Shows support info.",
                description_localizations: {"pt-BR":"ℹ️ Mostra info de suporte."},
                type: 1,
                options: [],
            },
            {
                name: "time",
                description: "🕐 Shows time in a timezone (WorldTimeAPI).",
                description_localizations: {"pt-BR":"🕐 Mostra hora num fuso (WorldTimeAPI)."},
                type: 1,
                options: [{"name":"zone","name_localizations":{"pt-BR":"zona"},"description":"ex: America/Sao_Paulo","description_localizations":{"pt-BR":"ex: America/Sao_Paulo"},"type":3,"required":true}],
            },
            {
                name: "timestamp",
                description: "⏰ Converts date to Discord timestamp.",
                description_localizations: {"pt-BR":"⏰ Converte data p/ timestamp do Discord."},
                type: 1,
                options: [{"name":"date","name_localizations":{"pt-BR":"data"},"description":"YYYY-MM-DD HH:mm (UTC)","description_localizations":{"pt-BR":"AAAA-MM-DD HH:mm (UTC)"},"type":3,"required":true}],
            },
            {
                name: "translate",
                description: "🌐 Translates text (MyMemory, no key).",
                description_localizations: {"pt-BR":"🌐 Traduz texto (MyMemory, sem chave)."},
                type: 1,
                options: [{"name":"text","name_localizations":{"pt-BR":"texto"},"description":"Text","description_localizations":{"pt-BR":"Texto"},"type":3,"required":true},{"name":"to","name_localizations":{"pt-BR":"para"},"description":"Target lang (ex: pt, en)","description_localizations":{"pt-BR":"Idioma destino (ex: pt, en)"},"type":3,"required":true}],
            },
            {
                name: "uptime",
                description: "ℹ️ Shows bot uptime.",
                description_localizations: {"pt-BR":"ℹ️ Mostra uptime do bot."},
                type: 1,
                options: [],
            },
            {
                name: "vote",
                description: "🗳️ Quick yes/no vote.",
                description_localizations: {"pt-BR":"🗳️ Votação rápida sim/não."},
                type: 1,
                options: [{"name":"topic","name_localizations":{"pt-BR":"tema"},"description":"Topic","description_localizations":{"pt-BR":"Tema"},"type":3,"required":true}],
            },
            {
                name: "weather",
                description: "🌤️ Shows weather via wttr.in.",
                description_localizations: {"pt-BR":"🌤️ Mostra o clima via wttr.in."},
                type: 1,
                options: [{"name":"city","name_localizations":{"pt-BR":"cidade"},"description":"City","description_localizations":{"pt-BR":"Cidade"},"type":3,"required":true}],
            },
        ],
    },
    /**
     * @param {DiscordBot} client
     * @param {ChatInputCommandInteraction} interaction
     */
    run: async (client, interaction) => {
        const sub = interaction.options.getSubcommand();
        const need = SUB_PERMS[sub];
        if (need) {
            let ok = false;
            try { ok = !!interaction.memberPermissions && interaction.memberPermissions.has(BigInt(need)); } catch { ok = false; }
            if (!ok) {
                const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
                return interaction.reply({ content: t('handler.missing_permissions', { locale }), ephemeral: true });
            }
        }
        const fn = handlers[sub];
        if (!fn) {
            return interaction.reply({ content: 'Unknown subcommand: ' + sub, ephemeral: true });
        }
        return fn(client, interaction);
    },
}).toJSON();
