// Grouped from 2 flat commands (Embed/slashcommand-embed-create.js, Embed/slashcommand-embed-send.js). Generated by scripts/group-commands.js.
const { ChatInputCommandInteraction } = require('discord.js');
const DiscordBot = require('../../client/DiscordBot');
const ApplicationCommand = require('../../structure/ApplicationCommand');
const { t, resolveLocale } = require('../../utils/i18n');
const { PermissionFlagsBits } = require('discord.js');
const { successEmbed, errorEmbed, infoEmbed } = require('../../utils/embeds');

const SUB_PERMS = {
    "embed-create": "8192",
    "embed-send": "8192",
};

const handlers = {
    "embed-create": async (client, interaction) => {
        const { EmbedBuilder } = require('discord.js');
        const title = interaction.options.getString('title', true);
        let color = (interaction.options.getString('color') || '#ffffff').replace('#', '');
        if (!/^[0-9a-fA-F]{6}$/.test(color)) color = 'ffffff';
        const desc = interaction.options.getString('description', true);
        const e = new EmbedBuilder().setColor(parseInt(color, 16)).setTitle(title.slice(0, 256)).setDescription(desc.slice(0, 4000)).setTimestamp();
        client.database.set('draftembed-' + interaction.guildId + '-' + interaction.user.id, { title, description: desc, color });
        return interaction.reply({ embeds: [e] });
    },
    "embed-send": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const { EmbedBuilder } = require('discord.js');
        const ch = interaction.options.getChannel('channel', true);
        const d = client.database.get('draftembed-' + interaction.guildId + '-' + interaction.user.id);
        if (!d) return interaction.reply({ embeds: [errorEmbed(locale, t('embed.nodraft', { locale }))], ephemeral: true });
        const e = new EmbedBuilder().setColor(parseInt(d.color, 16)).setTitle(d.title).setDescription(d.description).setTimestamp();
        if (!ch.isTextBased()) return interaction.reply({ embeds: [errorEmbed(locale, t('embed.notext', { locale }))], ephemeral: true });
        await ch.send({ embeds: [e] });
        return interaction.reply({ embeds: [successEmbed(locale, t('embed.sent', { locale }))] });
    },
};

module.exports = new ApplicationCommand({
    command: {
        name: "embed", description: "📦 Embed builder.", type: 1,
        description_localizations: { 'pt-BR': "📦 Criador de embeds." },
        default_member_permissions: "8192",
        options: [
            {
                name: "embed-create",
                description: "🧱 Builds an embed preview.",
                description_localizations: {"pt-BR":"🧱 Monta preview de embed."},
                type: 1,
                options: [{"name":"title","name_localizations":{"pt-BR":"titulo"},"description":"Title","description_localizations":{"pt-BR":"Título"},"type":3,"required":true},{"name":"description","name_localizations":{"pt-BR":"descricao"},"description":"Description","description_localizations":{"pt-BR":"Descrição"},"type":3,"required":true},{"name":"color","name_localizations":{"pt-BR":"cor"},"description":"Hex (ex: #ffffff)","description_localizations":{"pt-BR":"Hex (ex: #ffffff)"},"type":3}],
            },
            {
                name: "embed-send",
                description: "🧱 Sends your saved embed draft to a channel.",
                description_localizations: {"pt-BR":"🧱 Envia seu rascunho de embed num canal."},
                type: 1,
                options: [{"name":"channel","name_localizations":{"pt-BR":"canal"},"description":"Channel","description_localizations":{"pt-BR":"Canal"},"type":7,"required":true}],
            },
        ],
    },
    /**
     * @param {DiscordBot} client
     * @param {ChatInputCommandInteraction} interaction
     */
    run: async (client, interaction) => {
        const sub = interaction.options.getSubcommand();
        const need = SUB_PERMS[sub];
        if (need) {
            let ok = false;
            try { ok = !!interaction.memberPermissions && interaction.memberPermissions.has(BigInt(need)); } catch { ok = false; }
            if (!ok) {
                const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
                return interaction.reply({ content: t('handler.missing_permissions', { locale }), ephemeral: true });
            }
        }
        const fn = handlers[sub];
        if (!fn) {
            return interaction.reply({ content: 'Unknown subcommand: ' + sub, ephemeral: true });
        }
        return fn(client, interaction);
    },
}).toJSON();
