// Grouped from 6 flat commands (Welcome/slashcommand-autorole-remove.js, Welcome/slashcommand-autorole.js, Welcome/slashcommand-join-dm.js, Welcome/slashcommand-setgoodbye.js, Welcome/slashcommand-setwelcome.js, Welcome/slashcommand-welcome-test.js). Generated by scripts/group-commands.js.
const { ChatInputCommandInteraction } = require('discord.js');
const DiscordBot = require('../../client/DiscordBot');
const ApplicationCommand = require('../../structure/ApplicationCommand');
const { t, resolveLocale } = require('../../utils/i18n');
const { PermissionFlagsBits } = require('discord.js');
const { successEmbed, errorEmbed, infoEmbed } = require('../../utils/embeds');

const SUB_PERMS = {
    "autorole": "32",
    "autorole-remove": "32",
    "join-dm": "32",
    "setgoodbye": "32",
    "setwelcome": "32",
    "welcome-test": "32",
};

const handlers = {
    "autorole": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const role = interaction.options.getRole('role', true);
        const arr = client.database.get('autoroles-' + interaction.guildId) || [];
        if (!arr.includes(role.id)) arr.push(role.id);
        client.database.set('autoroles-' + interaction.guildId, arr);
        return interaction.reply({ embeds: [successEmbed(locale, t('autorole.ok', { locale, vars: { role: role.id } }))] });
    },
    "autorole-remove": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const role = interaction.options.getRole('role', true);
        const arr = (client.database.get('autoroles-' + interaction.guildId) || []).filter(id => id !== role.id);
        client.database.set('autoroles-' + interaction.guildId, arr);
        return interaction.reply({ embeds: [successEmbed(locale, t('autorole.removed', { locale, vars: { role: role.id } }))] });
    },
    "join-dm": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const message = interaction.options.getString('message');
        client.database.set('joindm-' + interaction.guildId, message || null);
        return interaction.reply({ embeds: [successEmbed(locale, t('joindm.ok', { locale }))] });
    },
    "setgoodbye": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const ch = interaction.options.getChannel('channel', true);
        const message = interaction.options.getString('message') || null;
        client.database.set('goodbye-' + interaction.guildId, { channel: ch.id, message });
        return interaction.reply({ embeds: [successEmbed(locale, t('welcome.ok', { locale, vars: { ch: ch.id } }))] });
    },
    "setwelcome": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const ch = interaction.options.getChannel('channel', true);
        const message = interaction.options.getString('message') || null;
        client.database.set('welcome-' + interaction.guildId, { channel: ch.id, message });
        return interaction.reply({ embeds: [successEmbed(locale, t('welcome.ok', { locale, vars: { ch: ch.id } }))] });
    },
    "welcome-test": async (client, interaction) => {
        const cfg = client.database.get('welcome-' + interaction.guildId) || {};
        const ch = cfg.channel ? await client.channels.fetch(cfg.channel).catch(() => interaction.channel) : interaction.channel;
        const msg = (cfg.message || 'Welcome {user} to {server}').replace('{user}', '<@' + interaction.user.id + '>').replace('{server}', interaction.guild.name);
        if (ch && ch.isTextBased()) await ch.send(msg);
        return interaction.reply({ content: 'OK', ephemeral: true });
    },
};

module.exports = new ApplicationCommand({
    command: {
        name: "welcome", description: "👋 Welcome and goodbye setup.", type: 1,
        description_localizations: { 'pt-BR': "👋 Configuração de boas-vindas e despedidas." },
        default_member_permissions: "32",
        options: [
            {
                name: "autorole",
                description: "👋 Sets the auto-role for new members.",
                description_localizations: {"pt-BR":"👋 Define cargo automático p/ novatos."},
                type: 1,
                options: [{"name":"role","name_localizations":{"pt-BR":"cargo"},"description":"Role","description_localizations":{"pt-BR":"Cargo"},"type":8,"required":true}],
            },
            {
                name: "autorole-remove",
                description: "👋 Removes an auto-role.",
                description_localizations: {"pt-BR":"👋 Remove um cargo automático."},
                type: 1,
                options: [{"name":"role","name_localizations":{"pt-BR":"cargo"},"description":"Role","description_localizations":{"pt-BR":"Cargo"},"type":8,"required":true}],
            },
            {
                name: "join-dm",
                description: "👋 Sets the DM sent to new members.",
                description_localizations: {"pt-BR":"👋 Define DM enviada a novatos."},
                type: 1,
                options: [{"name":"message","name_localizations":{"pt-BR":"mensagem"},"description":"Message (empty = disable)","description_localizations":{"pt-BR":"Mensagem (vazio = desliga)"},"type":3}],
            },
            {
                name: "setgoodbye",
                description: "👋 Sets the goodbye channel+message.",
                description_localizations: {"pt-BR":"👋 Define canal+mensagem de despedida."},
                type: 1,
                options: [{"name":"channel","name_localizations":{"pt-BR":"canal"},"description":"Channel","description_localizations":{"pt-BR":"Canal"},"type":7,"required":true},{"name":"message","name_localizations":{"pt-BR":"mensagem"},"description":"Use {user} {server}","description_localizations":{"pt-BR":"Use {user} {server}"},"type":3}],
            },
            {
                name: "setwelcome",
                description: "👋 Sets the welcome channel+message.",
                description_localizations: {"pt-BR":"👋 Define canal+mensagem de boas-vindas."},
                type: 1,
                options: [{"name":"channel","name_localizations":{"pt-BR":"canal"},"description":"Channel","description_localizations":{"pt-BR":"Canal"},"type":7,"required":true},{"name":"message","name_localizations":{"pt-BR":"mensagem"},"description":"Use {user} {server}","description_localizations":{"pt-BR":"Use {user} {server}"},"type":3}],
            },
            {
                name: "welcome-test",
                description: "👋 Sends a welcome test message.",
                description_localizations: {"pt-BR":"👋 Envia mensagem de teste de boas-vindas."},
                type: 1,
                options: [],
            },
        ],
    },
    /**
     * @param {DiscordBot} client
     * @param {ChatInputCommandInteraction} interaction
     */
    run: async (client, interaction) => {
        const sub = interaction.options.getSubcommand();
        const need = SUB_PERMS[sub];
        if (need) {
            let ok = false;
            try { ok = !!interaction.memberPermissions && interaction.memberPermissions.has(BigInt(need)); } catch { ok = false; }
            if (!ok) {
                const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
                return interaction.reply({ content: t('handler.missing_permissions', { locale }), ephemeral: true });
            }
        }
        const fn = handlers[sub];
        if (!fn) {
            return interaction.reply({ content: 'Unknown subcommand: ' + sub, ephemeral: true });
        }
        return fn(client, interaction);
    },
}).toJSON();
