// Grouped from 12 flat commands (Tickets/slashcommand-ticket-add.js, Tickets/slashcommand-ticket-claim.js, Tickets/slashcommand-ticket-close.js, Tickets/slashcommand-ticket-delete.js, Tickets/slashcommand-ticket-escalate.js, Tickets/slashcommand-ticket-form.js, Tickets/slashcommand-ticket-remove.js, Tickets/slashcommand-ticket-rename.js, Tickets/slashcommand-ticket-reopen.js, Tickets/slashcommand-ticket-setup.js, Tickets/slashcommand-ticket-stats.js, Tickets/slashcommand-ticket-transcript.js). Generated by scripts/group-commands.js.
const { ChatInputCommandInteraction } = require('discord.js');
const DiscordBot = require('../../client/DiscordBot');
const ApplicationCommand = require('../../structure/ApplicationCommand');
const { t, resolveLocale } = require('../../utils/i18n');
const { PermissionFlagsBits } = require('discord.js');
const { successEmbed, errorEmbed, infoEmbed } = require('../../utils/embeds');

const SUB_PERMS = {
    "ticket-add": "16",
    "ticket-claim": "16",
    "ticket-close": "16",
    "ticket-delete": "16",
    "ticket-escalate": "16",
    "ticket-form": "16",
    "ticket-remove": "16",
    "ticket-rename": "16",
    "ticket-reopen": "16",
    "ticket-setup": "32",
    "ticket-stats": "16",
    "ticket-transcript": "16",
};

const handlers = {
    "ticket-add": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user', true);
        try { await interaction.channel.permissionOverwrites.edit(user.id, { ViewChannel: true, SendMessages: true }); return interaction.reply({ embeds: [successEmbed(locale, t('ticket.added', { locale, vars: { user: user.tag } }))] }); }
        catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
    "ticket-claim": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const d = client.database.get('tickets-' + interaction.guildId) || {};
        d[interaction.channelId] = 'claimed:' + interaction.user.id;
        client.database.set('tickets-' + interaction.guildId, d);
        return interaction.reply({ embeds: [successEmbed(locale, t('ticket.claimed', { locale, vars: { user: interaction.user.tag } }))] });
    },
    "ticket-close": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        try { await interaction.channel.permissionOverwrites.edit(interaction.guild.roles.everyone, { SendMessages: false }); const d = client.database.get('tickets-' + interaction.guildId) || {}; d[interaction.channelId] = 'closed'; client.database.set('tickets-' + interaction.guildId, d); return interaction.reply({ embeds: [successEmbed(locale, t('ticket.closed', { locale }))] }); }
        catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
    "ticket-delete": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        await interaction.reply({ embeds: [successEmbed(locale, t('ticket.deleting', { locale }))] });
        setTimeout(() => { interaction.channel.delete().catch(() => null); }, 3000);
        return undefined;
    },
    "ticket-escalate": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const text = interaction.options.getString('text', true);
        const d = client.database.get('tickets-' + interaction.guildId) || {};
        d[interaction.channelId] = 'escalated:' + text.slice(0, 200);
        client.database.set('tickets-' + interaction.guildId, d);
        return interaction.reply({ embeds: [successEmbed(locale, t('ticket.escalated', { locale }))] });
    },
    "ticket-form": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const text = interaction.options.getString('text', true);
        await interaction.channel.send(text.slice(0, 1900));
        return interaction.reply({ embeds: [successEmbed(locale, t('ticket.form', { locale }))] });
    },
    "ticket-remove": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user', true);
        try { await interaction.channel.permissionOverwrites.delete(user.id); return interaction.reply({ embeds: [successEmbed(locale, t('ticket.removed', { locale, vars: { user: user.tag } }))] }); }
        catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
    "ticket-rename": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const name = interaction.options.getString('name', true);
        try { await interaction.channel.setName(name.slice(0, 90)); return interaction.reply({ embeds: [successEmbed(locale, t('ticket.renamed', { locale, vars: { name } }))] }); }
        catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
    "ticket-reopen": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        try { await interaction.channel.permissionOverwrites.edit(interaction.guild.roles.everyone, { SendMessages: null }); const d = client.database.get('tickets-' + interaction.guildId) || {}; d[interaction.channelId] = 'open'; client.database.set('tickets-' + interaction.guildId, d); return interaction.reply({ embeds: [successEmbed(locale, t('ticket.reopened', { locale }))] }); }
        catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
    "ticket-setup": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const { ActionRowBuilder, ButtonBuilder, ButtonStyle } = require('discord.js');
        const ch = interaction.options.getChannel('channel') || interaction.channel;
        if (!ch.isTextBased()) return interaction.reply({ embeds: [errorEmbed(locale, t('embed.notext', { locale }))], ephemeral: true });
        const row = new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket-open').setLabel('Open ticket').setStyle(ButtonStyle.Primary));
        await ch.send({ content: t('ticket.panel', { locale }), components: [row] });
        return interaction.reply({ embeds: [successEmbed(locale, t('ticket.setup', { locale }))] });
    },
    "ticket-stats": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const d = client.database.get('tickets-' + interaction.guildId) || {};
        const ids = Object.keys(d);
        if (!ids.length) return interaction.reply({ embeds: [infoEmbed(locale, t('ticket.nostats', { locale }))], ephemeral: true });
        return interaction.reply({ embeds: [infoEmbed(locale, t('ticket.stats', { locale, vars: { n: ids.length } }))] });
    },
    "ticket-transcript": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        await interaction.deferReply();
        try {
            const msgs = await interaction.channel.messages.fetch({ limit: 100 });
            const txt = [...msgs.values()].reverse().map(m => m.author.tag + ': ' + (m.content || '[embed]').slice(0, 500)).join('\n').slice(0, 15000);
            return interaction.editReply({ content: txt.slice(0, 1900) || t('ticket.empty', { locale }) });
        } catch (e) { return interaction.editReply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))] }); }
    },
};

module.exports = new ApplicationCommand({
    command: {
        name: "ticket", description: "🎫 Ticket system.", type: 1,
        description_localizations: { 'pt-BR': "🎫 Sistema de tickets." },
        options: [
            {
                name: "ticket-add",
                description: "🎫 Adds a member to the ticket.",
                description_localizations: {"pt-BR":"🎫 Adiciona membro ao ticket."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Member","description_localizations":{"pt-BR":"Membro"},"type":6,"required":true}],
            },
            {
                name: "ticket-claim",
                description: "🎫 Claims the ticket.",
                description_localizations: {"pt-BR":"🎫 Assume o ticket."},
                type: 1,
                options: [],
            },
            {
                name: "ticket-close",
                description: "🎫 Closes the ticket.",
                description_localizations: {"pt-BR":"🎫 Fecha o ticket."},
                type: 1,
                options: [],
            },
            {
                name: "ticket-delete",
                description: "🎫 Deletes the ticket channel.",
                description_localizations: {"pt-BR":"🎫 Apaga o canal do ticket."},
                type: 1,
                options: [],
            },
            {
                name: "ticket-escalate",
                description: "🎫 Escalates the ticket with a note.",
                description_localizations: {"pt-BR":"🎫 Escala o ticket com nota."},
                type: 1,
                options: [{"name":"text","name_localizations":{"pt-BR":"texto"},"description":"Text","description_localizations":{"pt-BR":"Texto"},"type":3,"required":true}],
            },
            {
                name: "ticket-form",
                description: "🎫 Posts a form question in the ticket.",
                description_localizations: {"pt-BR":"🎫 Posta pergunta de formulário no ticket."},
                type: 1,
                options: [{"name":"text","name_localizations":{"pt-BR":"texto"},"description":"Text","description_localizations":{"pt-BR":"Texto"},"type":3,"required":true}],
            },
            {
                name: "ticket-remove",
                description: "🎫 Removes a member from the ticket.",
                description_localizations: {"pt-BR":"🎫 Remove membro do ticket."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Member","description_localizations":{"pt-BR":"Membro"},"type":6,"required":true}],
            },
            {
                name: "ticket-rename",
                description: "🎫 Renames the ticket channel.",
                description_localizations: {"pt-BR":"🎫 Renomeia o canal do ticket."},
                type: 1,
                options: [{"name":"name","description":"New name","description_localizations":{"pt-BR":"Novo nome"},"type":3,"required":true}],
            },
            {
                name: "ticket-reopen",
                description: "🎫 Reopens the ticket.",
                description_localizations: {"pt-BR":"🎫 Reabre o ticket."},
                type: 1,
                options: [],
            },
            {
                name: "ticket-setup",
                description: "🎫 Posts the ticket panel with button.",
                description_localizations: {"pt-BR":"🎫 Posta painel de tickets com botão."},
                type: 1,
                options: [{"name":"channel","name_localizations":{"pt-BR":"canal"},"description":"Panel channel (empty = current)","description_localizations":{"pt-BR":"Canal do painel (vazio = atual)"},"type":7}],
            },
            {
                name: "ticket-stats",
                description: "🎫 Shows ticket stats.",
                description_localizations: {"pt-BR":"🎫 Mostra stats de tickets."},
                type: 1,
                options: [],
            },
            {
                name: "ticket-transcript",
                description: "🎫 Saves a text transcript.",
                description_localizations: {"pt-BR":"🎫 Salva transcrição em texto."},
                type: 1,
                options: [],
            },
        ],
    },
    /**
     * @param {DiscordBot} client
     * @param {ChatInputCommandInteraction} interaction
     */
    run: async (client, interaction) => {
        const sub = interaction.options.getSubcommand();
        const need = SUB_PERMS[sub];
        if (need) {
            let ok = false;
            try { ok = !!interaction.memberPermissions && interaction.memberPermissions.has(BigInt(need)); } catch { ok = false; }
            if (!ok) {
                const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
                return interaction.reply({ content: t('handler.missing_permissions', { locale }), ephemeral: true });
            }
        }
        const fn = handlers[sub];
        if (!fn) {
            return interaction.reply({ content: 'Unknown subcommand: ' + sub, ephemeral: true });
        }
        return fn(client, interaction);
    },
}).toJSON();
