// Grouped from 5 flat commands (Roles/slashcommand-rr-list.js, Roles/slashcommand-rr-remove.js, Roles/slashcommand-rr.js, Roles/slashcommand-selfroles.js, Roles/slashcommand-temprole.js). Generated by scripts/group-commands.js.
const { ChatInputCommandInteraction } = require('discord.js');
const DiscordBot = require('../../client/DiscordBot');
const ApplicationCommand = require('../../structure/ApplicationCommand');
const { t, resolveLocale } = require('../../utils/i18n');
const { successEmbed, errorEmbed, infoEmbed } = require('../../utils/embeds');
const { PermissionFlagsBits } = require('discord.js');

const SUB_PERMS = {
    "rr": "268435456",
    "rr-remove": "268435456",
    "temprole": "268435456",
};

const handlers = {
    "rr": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const role = interaction.options.getRole('role', true);
        const emoji = interaction.options.getString('emoji', true);
        const text = interaction.options.getString('text') || role.name;
        const msg = await interaction.channel.send('**' + text + '** — ' + emoji);
        try { await msg.react(emoji); } catch { return interaction.reply({ embeds: [errorEmbed(locale, t('rr.bademoji', { locale }))], ephemeral: true }); }
        const all = client.database.get('rr-' + interaction.guildId) || [];
        all.push({ messageId: msg.id, channelId: msg.channelId, emoji, roleId: role.id });
        client.database.set('rr-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('rr.ok', { locale }))], ephemeral: true });
    },
    "rr-list": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const all = client.database.get('rr-' + interaction.guildId) || [];
        if (!all.length) return interaction.reply({ embeds: [infoEmbed(locale, t('rr.empty', { locale }))], ephemeral: true });
        return interaction.reply({ embeds: [infoEmbed(locale, all.map(r => r.emoji + ' -> <@&' + r.roleId + '> (' + r.messageId + ')').join('\n').slice(0, 3500))] });
    },
    "rr-remove": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const mid = interaction.options.getString('message', true);
        const all = (client.database.get('rr-' + interaction.guildId) || []).filter(x => x.messageId !== mid);
        client.database.set('rr-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('rr.removed', { locale }))] });
    },
    "selfroles": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const all = client.database.get('rr-' + interaction.guildId) || [];
        if (!all.length) return interaction.reply({ embeds: [infoEmbed(locale, t('rr.empty', { locale }))], ephemeral: true });
        return interaction.reply({ embeds: [infoEmbed(locale, all.map(r => r.emoji + ' <@&' + r.roleId + '>').join(' ').slice(0, 3500))] });
    },
    "temprole": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user', true);
        const role = interaction.options.getRole('role', true);
        const minutes = Math.max(1, interaction.options.getInteger('minutes', true));
        const member = await interaction.guild.members.fetch(user.id).catch(() => null);
        if (!member) return interaction.reply({ embeds: [errorEmbed(locale, t('common.member_not_found', { locale }))], ephemeral: true });
        try {
            await member.roles.add(role);
            setTimeout(() => { member.roles.remove(role).catch(() => null); }, minutes * 60000);
            return interaction.reply({ embeds: [successEmbed(locale, t('temprole.ok', { locale, vars: { user: user.tag, minutes } }))] });
        } catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
};

module.exports = new ApplicationCommand({
    command: {
        name: "roles", description: "🎭 Reaction and managed roles.", type: 1,
        description_localizations: { 'pt-BR': "🎭 Cargos por reação e gerenciados." },
        options: [
            {
                name: "rr",
                description: "🎭 Creates a reaction-role message.",
                description_localizations: {"pt-BR":"🎭 Cria mensagem de cargo por reação."},
                type: 1,
                options: [{"name":"role","name_localizations":{"pt-BR":"cargo"},"description":"Role","description_localizations":{"pt-BR":"Cargo"},"type":8,"required":true},{"name":"emoji","description":"Emoji","description_localizations":{"pt-BR":"Emoji"},"type":3,"required":true},{"name":"text","name_localizations":{"pt-BR":"texto"},"description":"Message text","description_localizations":{"pt-BR":"Texto da mensagem"},"type":3}],
            },
            {
                name: "rr-list",
                description: "🎭 Lists reaction-roles.",
                description_localizations: {"pt-BR":"🎭 Lista cargos por reação."},
                type: 1,
                options: [],
            },
            {
                name: "rr-remove",
                description: "🎭 Removes a reaction-role by message ID.",
                description_localizations: {"pt-BR":"🎭 Remove cargo por reação via ID da msg."},
                type: 1,
                options: [{"name":"message","name_localizations":{"pt-BR":"mensagem"},"description":"Message ID","description_localizations":{"pt-BR":"ID da mensagem"},"type":3,"required":true}],
            },
            {
                name: "selfroles",
                description: "🎭 Shows self-assignable roles.",
                description_localizations: {"pt-BR":"🎭 Mostra cargos auto-atribuíveis."},
                type: 1,
                options: [],
            },
            {
                name: "temprole",
                description: "⏳ Gives a role temporarily (minutes).",
                description_localizations: {"pt-BR":"⏳ Dá cargo temporário (minutos)."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Member","description_localizations":{"pt-BR":"Membro"},"type":6,"required":true},{"name":"role","name_localizations":{"pt-BR":"cargo"},"description":"Role","description_localizations":{"pt-BR":"Cargo"},"type":8,"required":true},{"name":"minutes","name_localizations":{"pt-BR":"minutos"},"description":"Minutes","description_localizations":{"pt-BR":"Minutos"},"type":4,"required":true}],
            },
        ],
    },
    /**
     * @param {DiscordBot} client
     * @param {ChatInputCommandInteraction} interaction
     */
    run: async (client, interaction) => {
        const sub = interaction.options.getSubcommand();
        const need = SUB_PERMS[sub];
        if (need) {
            let ok = false;
            try { ok = !!interaction.memberPermissions && interaction.memberPermissions.has(BigInt(need)); } catch { ok = false; }
            if (!ok) {
                const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
                return interaction.reply({ content: t('handler.missing_permissions', { locale }), ephemeral: true });
            }
        }
        const fn = handlers[sub];
        if (!fn) {
            return interaction.reply({ content: 'Unknown subcommand: ' + sub, ephemeral: true });
        }
        return fn(client, interaction);
    },
}).toJSON();
