// Grouped from 8 flat commands (Levels/slashcommand-give-xp.js, Levels/slashcommand-leaderboard.js, Levels/slashcommand-level-message.js, Levels/slashcommand-level-reward.js, Levels/slashcommand-rank.js, Levels/slashcommand-remove-xp.js, Levels/slashcommand-reset-xp.js, Levels/slashcommand-xp.js). Generated by scripts/group-commands.js.
const { ChatInputCommandInteraction } = require('discord.js');
const DiscordBot = require('../../client/DiscordBot');
const ApplicationCommand = require('../../structure/ApplicationCommand');
const { t, resolveLocale } = require('../../utils/i18n');
const { PermissionFlagsBits } = require('discord.js');
const { successEmbed, errorEmbed, infoEmbed } = require('../../utils/embeds');

const SUB_PERMS = {
    "give-xp": "32",
    "level-message": "32",
    "level-reward": "32",
    "remove-xp": "32",
    "reset-xp": "32",
};

const handlers = {
    "give-xp": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user', true);
        const amount = interaction.options.getInteger('amount', true);
        const all = client.database.get('xp-' + interaction.guildId) || {};
        const d = all[user.id] || (all[user.id] = { xp: 0, level: 0 });
        d.xp = Math.max(0, d.xp + amount);
        d.level = Math.floor(Math.sqrt(d.xp) / 10);
        client.database.set('xp-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('xp.given', { locale, vars: { user: user.tag, amount, xp: d.xp } }))] });
    },
    "leaderboard": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const store = client.database.get('xp-' + interaction.guildId) || {};
        const top = Object.entries(store).sort((a, b) => (b[1].xp || 0) - (a[1].xp || 0)).slice(0, 10);
        if (!top.length) return interaction.reply({ embeds: [infoEmbed(locale, t('leaderboard.empty', { locale }))], ephemeral: true });
        return interaction.reply({ embeds: [infoEmbed(locale, top.map(([id, d], i) => (i + 1) + '. <@' + id + '> — L' + (d.level || 0) + ' (' + (d.xp || 0) + ' XP)').join('\n'))] });
    },
    "level-message": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const message = interaction.options.getString('message');
        const ch = interaction.options.getChannel('channel');
        client.database.set('levelmsg-' + interaction.guildId, message ? { message, channel: ch ? ch.id : null } : null);
        return interaction.reply({ embeds: [successEmbed(locale, t('levelmsg.ok', { locale }))] });
    },
    "level-reward": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const level = interaction.options.getInteger('level', true);
        const role = interaction.options.getRole('role', true);
        const all = client.database.get('levelrewards-' + interaction.guildId) || {};
        all[level] = role.id;
        client.database.set('levelrewards-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('levelreward.ok', { locale, vars: { level, role: role.id } }))] });
    },
    "rank": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const store = client.database.get('xp-' + interaction.guildId) || {};
        const user = interaction.options.getUser('user') || interaction.user;
        const d = store[user.id] || { xp: 0, level: 0 };
        return interaction.reply({ embeds: [infoEmbed(locale, t('rank.body', { locale, vars: { user: user.tag, level: d.level, xp: d.xp } }))] });
    },
    "remove-xp": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user', true);
        const amount = interaction.options.getInteger('amount', true);
        const all = client.database.get('xp-' + interaction.guildId) || {};
        const d = all[user.id] || (all[user.id] = { xp: 0, level: 0 });
        d.xp = Math.max(0, d.xp - amount);
        d.level = Math.floor(Math.sqrt(d.xp) / 10);
        client.database.set('xp-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('xp.removed', { locale, vars: { user: user.tag, amount, xp: d.xp } }))] });
    },
    "reset-xp": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user');
        if (user) { const all = client.database.get('xp-' + interaction.guildId) || {}; delete all[user.id]; client.database.set('xp-' + interaction.guildId, all); }
        else client.database.set('xp-' + interaction.guildId, {});
        return interaction.reply({ embeds: [successEmbed(locale, t('xp.reset', { locale }))] });
    },
    "xp": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const store = client.database.get('xp-' + interaction.guildId) || {};
        const user = interaction.options.getUser('user') || interaction.user;
        const d = store[user.id] || { xp: 0, level: 0 };
        return interaction.reply({ embeds: [infoEmbed(locale, t('xp.body', { locale, vars: { user: user.tag, xp: d.xp } }))] });
    },
};

module.exports = new ApplicationCommand({
    command: {
        name: "levels", description: "📈 Level and XP commands.", type: 1,
        description_localizations: { 'pt-BR': "📈 Comandos de níveis e XP." },
        options: [
            {
                name: "give-xp",
                description: "⭐ Gives XP to a member.",
                description_localizations: {"pt-BR":"⭐ Dá XP a um membro."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Member","description_localizations":{"pt-BR":"Membro"},"type":6,"required":true},{"name":"amount","name_localizations":{"pt-BR":"quantidade"},"description":"Amount","description_localizations":{"pt-BR":"Quantidade"},"type":4,"required":true}],
            },
            {
                name: "leaderboard",
                description: "⭐ XP leaderboard.",
                description_localizations: {"pt-BR":"⭐ Ranking de XP."},
                type: 1,
                options: [],
            },
            {
                name: "level-message",
                description: "⭐ Sets level-up message/channel.",
                description_localizations: {"pt-BR":"⭐ Define mensagem/canal de level-up."},
                type: 1,
                options: [{"name":"message","name_localizations":{"pt-BR":"mensagem"},"description":"Use {user} {level} (empty = disable)","description_localizations":{"pt-BR":"Use {user} {level} (vazio = desliga)"},"type":3},{"name":"channel","name_localizations":{"pt-BR":"canal"},"description":"Channel (empty = current)","description_localizations":{"pt-BR":"Canal (vazio = atual)"},"type":7}],
            },
            {
                name: "level-reward",
                description: "⭐ Sets role reward for a level.",
                description_localizations: {"pt-BR":"⭐ Define cargo de recompensa por nível."},
                type: 1,
                options: [{"name":"level","name_localizations":{"pt-BR":"nivel"},"description":"Level","description_localizations":{"pt-BR":"Nível"},"type":4,"required":true},{"name":"role","name_localizations":{"pt-BR":"cargo"},"description":"Role","description_localizations":{"pt-BR":"Cargo"},"type":8,"required":true}],
            },
            {
                name: "rank",
                description: "⭐ Shows your (or a member) rank.",
                description_localizations: {"pt-BR":"⭐ Mostra seu rank (ou de membro)."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Member","description_localizations":{"pt-BR":"Membro"},"type":6}],
            },
            {
                name: "remove-xp",
                description: "⭐ Removes XP from a member.",
                description_localizations: {"pt-BR":"⭐ Remove XP de um membro."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Member","description_localizations":{"pt-BR":"Membro"},"type":6,"required":true},{"name":"amount","name_localizations":{"pt-BR":"quantidade"},"description":"Amount","description_localizations":{"pt-BR":"Quantidade"},"type":4,"required":true}],
            },
            {
                name: "reset-xp",
                description: "⭐ Resets XP (user or all).",
                description_localizations: {"pt-BR":"⭐ Reseta XP (usuário ou tudo)."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Member (empty = all)","description_localizations":{"pt-BR":"Membro (vazio = tudo)"},"type":6}],
            },
            {
                name: "xp",
                description: "⭐ Shows XP of a member.",
                description_localizations: {"pt-BR":"⭐ Mostra XP de um membro."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Member","description_localizations":{"pt-BR":"Membro"},"type":6}],
            },
        ],
    },
    /**
     * @param {DiscordBot} client
     * @param {ChatInputCommandInteraction} interaction
     */
    run: async (client, interaction) => {
        const sub = interaction.options.getSubcommand();
        const need = SUB_PERMS[sub];
        if (need) {
            let ok = false;
            try { ok = !!interaction.memberPermissions && interaction.memberPermissions.has(BigInt(need)); } catch { ok = false; }
            if (!ok) {
                const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
                return interaction.reply({ content: t('handler.missing_permissions', { locale }), ephemeral: true });
            }
        }
        const fn = handlers[sub];
        if (!fn) {
            return interaction.reply({ content: 'Unknown subcommand: ' + sub, ephemeral: true });
        }
        return fn(client, interaction);
    },
}).toJSON();
