// Grouped from 8 flat commands (Alerts/slashcommand-alert-kick.js, Alerts/slashcommand-alert-list.js, Alerts/slashcommand-alert-reddit.js, Alerts/slashcommand-alert-remove.js, Alerts/slashcommand-alert-rss.js, Alerts/slashcommand-alert-tiktok.js, Alerts/slashcommand-alert-twitch.js, Alerts/slashcommand-alert-youtube.js). Generated by scripts/group-commands.js.
const { ChatInputCommandInteraction } = require('discord.js');
const DiscordBot = require('../../client/DiscordBot');
const ApplicationCommand = require('../../structure/ApplicationCommand');
const { t, resolveLocale } = require('../../utils/i18n');
const { PermissionFlagsBits } = require('discord.js');
const { successEmbed, errorEmbed, infoEmbed } = require('../../utils/embeds');

const SUB_PERMS = {
    "alert-kick": "32",
    "alert-reddit": "32",
    "alert-remove": "32",
    "alert-rss": "32",
    "alert-tiktok": "32",
    "alert-twitch": "32",
    "alert-youtube": "32",
};

const handlers = {
    "alert-kick": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const source = interaction.options.getString('source', true);
        const ch = interaction.options.getChannel('channel', true);
        const all = client.database.get('alerts-' + interaction.guildId) || [];
        all.push({ type: 'alert-kick', source, channel: ch.id });
        client.database.set('alerts-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('alert.ok', { locale, vars: { type: 'Kick', source, ch: ch.id } }))] });
    },
    "alert-list": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const all = client.database.get('alerts-' + interaction.guildId) || [];
        if (!all.length) return interaction.reply({ embeds: [infoEmbed(locale, t('alert.empty', { locale }))], ephemeral: true });
        return interaction.reply({ embeds: [infoEmbed(locale, all.map((a, i) => (i + 1) + '. ' + a.type + ' **' + a.source + '** -> <#' + a.channel + '>').join('\n').slice(0, 3500))] });
    },
    "alert-reddit": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const source = interaction.options.getString('source', true);
        const ch = interaction.options.getChannel('channel', true);
        const all = client.database.get('alerts-' + interaction.guildId) || [];
        all.push({ type: 'alert-reddit', source, channel: ch.id });
        client.database.set('alerts-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('alert.ok', { locale, vars: { type: 'Reddit', source, ch: ch.id } }))] });
    },
    "alert-remove": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const n = interaction.options.getInteger('number', true);
        const all = client.database.get('alerts-' + interaction.guildId) || [];
        if (n < 1 || n > all.length) return interaction.reply({ embeds: [errorEmbed(locale, t('alert.notfound', { locale }))], ephemeral: true });
        all.splice(n - 1, 1);
        client.database.set('alerts-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('alert.removed', { locale, vars: { n } }))] });
    },
    "alert-rss": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const source = interaction.options.getString('source', true);
        const ch = interaction.options.getChannel('channel', true);
        const all = client.database.get('alerts-' + interaction.guildId) || [];
        all.push({ type: 'alert-rss', source, channel: ch.id });
        client.database.set('alerts-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('alert.ok', { locale, vars: { type: 'RSS', source, ch: ch.id } }))] });
    },
    "alert-tiktok": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const source = interaction.options.getString('source', true);
        const ch = interaction.options.getChannel('channel', true);
        const all = client.database.get('alerts-' + interaction.guildId) || [];
        all.push({ type: 'alert-tiktok', source, channel: ch.id });
        client.database.set('alerts-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('alert.ok', { locale, vars: { type: 'TikTok', source, ch: ch.id } }))] });
    },
    "alert-twitch": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const source = interaction.options.getString('source', true);
        const ch = interaction.options.getChannel('channel', true);
        const all = client.database.get('alerts-' + interaction.guildId) || [];
        all.push({ type: 'alert-twitch', source, channel: ch.id });
        client.database.set('alerts-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('alert.ok', { locale, vars: { type: 'Twitch', source, ch: ch.id } }))] });
    },
    "alert-youtube": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const source = interaction.options.getString('source', true);
        const ch = interaction.options.getChannel('channel', true);
        const all = client.database.get('alerts-' + interaction.guildId) || [];
        all.push({ type: 'alert-youtube', source, channel: ch.id });
        client.database.set('alerts-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('alert.ok', { locale, vars: { type: 'YouTube', source, ch: ch.id } }))] });
    },
};

module.exports = new ApplicationCommand({
    command: {
        name: "alerts", description: "🔔 External alerts (Twitch, YouTube...).", type: 1,
        description_localizations: { 'pt-BR': "🔔 Alertas externos (Twitch, YouTube...)." },
        options: [
            {
                name: "alert-kick",
                description: "🔔 Sets Kick alert (source + channel).",
                description_localizations: {"pt-BR":"🔔 Configura alerta de Kick (fonte + canal)."},
                type: 1,
                options: [{"name":"source","name_localizations":{"pt-BR":"fonte"},"description":"Channel name / URL","description_localizations":{"pt-BR":"Nome do canal / URL"},"type":3,"required":true},{"name":"channel","name_localizations":{"pt-BR":"canal"},"description":"Post channel","description_localizations":{"pt-BR":"Canal de postagem"},"type":7,"required":true}],
            },
            {
                name: "alert-list",
                description: "🔔 Lists alerts.",
                description_localizations: {"pt-BR":"🔔 Lista alertas."},
                type: 1,
                options: [],
            },
            {
                name: "alert-reddit",
                description: "🔔 Sets Reddit alert (source + channel).",
                description_localizations: {"pt-BR":"🔔 Configura alerta de Reddit (fonte + canal)."},
                type: 1,
                options: [{"name":"source","name_localizations":{"pt-BR":"fonte"},"description":"Channel name / URL","description_localizations":{"pt-BR":"Nome do canal / URL"},"type":3,"required":true},{"name":"channel","name_localizations":{"pt-BR":"canal"},"description":"Post channel","description_localizations":{"pt-BR":"Canal de postagem"},"type":7,"required":true}],
            },
            {
                name: "alert-remove",
                description: "🔔 Removes an alert by number.",
                description_localizations: {"pt-BR":"🔔 Remove um alerta por número."},
                type: 1,
                options: [{"name":"number","name_localizations":{"pt-BR":"numero"},"description":"Number from /alert-list","description_localizations":{"pt-BR":"Número do /alert-list"},"type":4,"required":true}],
            },
            {
                name: "alert-rss",
                description: "🔔 Sets RSS alert (source + channel).",
                description_localizations: {"pt-BR":"🔔 Configura alerta de RSS (fonte + canal)."},
                type: 1,
                options: [{"name":"source","name_localizations":{"pt-BR":"fonte"},"description":"Channel name / URL","description_localizations":{"pt-BR":"Nome do canal / URL"},"type":3,"required":true},{"name":"channel","name_localizations":{"pt-BR":"canal"},"description":"Post channel","description_localizations":{"pt-BR":"Canal de postagem"},"type":7,"required":true}],
            },
            {
                name: "alert-tiktok",
                description: "🔔 Sets TikTok alert (source + channel).",
                description_localizations: {"pt-BR":"🔔 Configura alerta de TikTok (fonte + canal)."},
                type: 1,
                options: [{"name":"source","name_localizations":{"pt-BR":"fonte"},"description":"Channel name / URL","description_localizations":{"pt-BR":"Nome do canal / URL"},"type":3,"required":true},{"name":"channel","name_localizations":{"pt-BR":"canal"},"description":"Post channel","description_localizations":{"pt-BR":"Canal de postagem"},"type":7,"required":true}],
            },
            {
                name: "alert-twitch",
                description: "🔔 Sets Twitch alert (source + channel).",
                description_localizations: {"pt-BR":"🔔 Configura alerta de Twitch (fonte + canal)."},
                type: 1,
                options: [{"name":"source","name_localizations":{"pt-BR":"fonte"},"description":"Channel name / URL","description_localizations":{"pt-BR":"Nome do canal / URL"},"type":3,"required":true},{"name":"channel","name_localizations":{"pt-BR":"canal"},"description":"Post channel","description_localizations":{"pt-BR":"Canal de postagem"},"type":7,"required":true}],
            },
            {
                name: "alert-youtube",
                description: "🔔 Sets YouTube alert (source + channel).",
                description_localizations: {"pt-BR":"🔔 Configura alerta de YouTube (fonte + canal)."},
                type: 1,
                options: [{"name":"source","name_localizations":{"pt-BR":"fonte"},"description":"Channel name / URL","description_localizations":{"pt-BR":"Nome do canal / URL"},"type":3,"required":true},{"name":"channel","name_localizations":{"pt-BR":"canal"},"description":"Post channel","description_localizations":{"pt-BR":"Canal de postagem"},"type":7,"required":true}],
            },
        ],
    },
    /**
     * @param {DiscordBot} client
     * @param {ChatInputCommandInteraction} interaction
     */
    run: async (client, interaction) => {
        const sub = interaction.options.getSubcommand();
        const need = SUB_PERMS[sub];
        if (need) {
            let ok = false;
            try { ok = !!interaction.memberPermissions && interaction.memberPermissions.has(BigInt(need)); } catch { ok = false; }
            if (!ok) {
                const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
                return interaction.reply({ content: t('handler.missing_permissions', { locale }), ephemeral: true });
            }
        }
        const fn = handlers[sub];
        if (!fn) {
            return interaction.reply({ content: 'Unknown subcommand: ' + sub, ephemeral: true });
        }
        return fn(client, interaction);
    },
}).toJSON();
