// Grouped from 25 flat commands (Admin/slashcommand-ban.js, Admin/slashcommand-case.js, Admin/slashcommand-clearwarn.js, Admin/slashcommand-hackban.js, Admin/slashcommand-history.js, Admin/slashcommand-kick.js, Admin/slashcommand-lock.js, Admin/slashcommand-lockdown.js, Admin/slashcommand-massban.js, Admin/slashcommand-modlog.js, Admin/slashcommand-modstats.js, Admin/slashcommand-nick.js, Admin/slashcommand-note.js, Admin/slashcommand-notes.js, Admin/slashcommand-purge.js, Admin/slashcommand-reason.js, Admin/slashcommand-report.js, Admin/slashcommand-slowmode.js, Admin/slashcommand-softban.js, Admin/slashcommand-tempban.js, Admin/slashcommand-tempmute.js, Admin/slashcommand-timeout.js, Admin/slashcommand-unban.js, Admin/slashcommand-unlock.js, Admin/slashcommand-unmute.js). Generated by scripts/group-commands.js.
const { ChatInputCommandInteraction } = require('discord.js');
const DiscordBot = require('../../client/DiscordBot');
const ApplicationCommand = require('../../structure/ApplicationCommand');
const { t, resolveLocale } = require('../../utils/i18n');
const { PermissionFlagsBits } = require('discord.js');
const { successEmbed, errorEmbed, infoEmbed } = require('../../utils/embeds');

const SUB_PERMS = {
    "ban": "4",
    "case": "1099511627776",
    "clearwarn": "1099511627776",
    "hackban": "4",
    "history": "1099511627776",
    "kick": "2",
    "lock": "16",
    "lockdown": "16",
    "massban": "4",
    "modlog": "1099511627776",
    "modstats": "1099511627776",
    "nick": "134217728",
    "note": "1099511627776",
    "notes": "1099511627776",
    "purge": "8192",
    "reason": "1099511627776",
    "slowmode": "16",
    "softban": "4",
    "tempban": "4",
    "tempmute": "1099511627776",
    "timeout": "1099511627776",
    "unban": "4",
    "unlock": "16",
    "unmute": "1099511627776",
};

const handlers = {
    "ban": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user', true);
        const reason = interaction.options.getString('reason') || 'No reason';
        const member = await interaction.guild.members.fetch(user.id).catch(() => null);
        if (!member) return interaction.reply({ content: t('ban.not_found', { locale }), ephemeral: true });
        try {
            await member.ban({ reason });
            return interaction.reply({ content: t('ban.success', { locale, vars: { user: user.tag, reason } }) });
        } catch (e) {
            return interaction.reply({ content: t('mod_error', { locale, vars: { error: e.message || e } }), ephemeral: true });
        }
    },
    "case": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const modstore = require('../../utils/modstore');
        const id = interaction.options.getInteger('id', true);
        const c = modstore.all(client.database, 'cases', interaction.guildId).find(x => x.id === id);
        if (!c) return interaction.reply({ embeds: [errorEmbed(locale, t('case.not_found', { locale }))], ephemeral: true });
        return interaction.reply({ embeds: [infoEmbed(locale, t('case.line', { locale, vars: { id: c.id, action: c.action, user: c.userId, reason: c.reason || '-', ts: c.ts } }))] });
    },
    "clearwarn": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const modstore = require('../../utils/modstore');
        const id = interaction.options.getInteger('id');
        if (id) {
            const ok = modstore.remove(client.database, 'warns', interaction.guildId, id);
            return interaction.reply({ embeds: [(ok ? successEmbed(locale, t('clearwarn.one', { locale, vars: { id } })) : errorEmbed(locale, t('clearwarn.not_found', { locale })))], ephemeral: !ok });
        }
        const user = interaction.options.getUser('user');
        const arr = modstore.all(client.database, 'warns', interaction.guildId);
        const keep = user ? arr.filter(w => w.userId !== user.id) : [];
        const n = arr.length - keep.length;
        client.database.set('warns-' + interaction.guildId, keep);
        return interaction.reply({ embeds: [successEmbed(locale, t('clearwarn.all', { locale, vars: { n } }))] });
    },
    "hackban": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const id = interaction.options.getString('id', true);
        const reason = interaction.options.getString('reason') || 'No reason';
        try {
            await interaction.guild.members.ban(id, { reason });
            return interaction.reply({ embeds: [successEmbed(locale, t('hackban.success', { locale, vars: { id } }))] });
        } catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
    "history": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const modstore = require('../../utils/modstore');
        const user = interaction.options.getUser('user', true);
        const warns = modstore.all(client.database, 'warns', interaction.guildId).filter(w => w.userId === user.id);
        const notes = modstore.all(client.database, 'notes', interaction.guildId).filter(w => w.userId === user.id);
        if (!warns.length && !notes.length) return interaction.reply({ embeds: [infoEmbed(locale, t('history.empty', { locale }))], ephemeral: true });
        const lines = [...warns.map(w => '[warn #' + w.id + '] ' + w.reason), ...notes.map(w => '[note #' + w.id + '] ' + w.text)].join('\n').slice(0, 3500);
        return interaction.reply({ embeds: [infoEmbed(locale, lines)] });
    },
    "kick": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user', true);
        const reason = interaction.options.getString('reason') || 'No reason';
        const member = await interaction.guild.members.fetch(user.id).catch(() => null);
        if (!member) return interaction.reply({ content: t('kick.not_found', { locale }), ephemeral: true });
        try {
            await member.kick(reason);
            return interaction.reply({ content: t('kick.success', { locale, vars: { user: user.tag, reason } }) });
        } catch (e) {
            return interaction.reply({ content: t('mod_error', { locale, vars: { error: e.message || e } }), ephemeral: true });
        }
    },
    "lock": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        try {
            await interaction.channel.permissionOverwrites.edit(interaction.guild.roles.everyone, { SendMessages: false });
            return interaction.reply({ embeds: [successEmbed(locale, t('lock.locked', { locale }))] });
        } catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
    "lockdown": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const state = interaction.options.getString('state', true);
        const val = state === 'on' ? false : null;
        let n = 0;
        for (const [, ch] of interaction.guild.channels.cache.filter(c => c.isTextBased() && !c.isThread())) {
            try { await ch.permissionOverwrites.edit(interaction.guild.roles.everyone, { SendMessages: val }); n++; } catch {}
        }
        return interaction.reply({ embeds: [successEmbed(locale, t(state === 'on' ? 'lockdown.on' : 'lockdown.off', { locale }) + ' (' + n + ')')] });
    },
    "massban": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const ids = interaction.options.getString('ids', true).split(/\s+/).filter(Boolean).slice(0, 20);
        const reason = interaction.options.getString('reason') || 'No reason';
        let n = 0;
        for (const id of ids) { try { await interaction.guild.members.ban(id, { reason }); n++; } catch {} }
        return interaction.reply({ embeds: [successEmbed(locale, t('massban.success', { locale, vars: { n } }))] });
    },
    "modlog": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const modstore = require('../../utils/modstore');
        const limit = Math.min(10, Math.max(1, interaction.options.getInteger('limit') || 5));
        const cases = modstore.all(client.database, 'cases', interaction.guildId).slice(-limit).reverse();
        if (!cases.length) return interaction.reply({ embeds: [infoEmbed(locale, t('modlog.empty', { locale }))], ephemeral: true });
        const lines = cases.map(c => t('case.line', { locale, vars: { id: c.id, action: c.action, user: c.userId, reason: c.reason || '-', ts: c.ts } })).join('\n');
        return interaction.reply({ embeds: [infoEmbed(locale, lines)] });
    },
    "modstats": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const modstore = require('../../utils/modstore');
        const cases = modstore.all(client.database, 'cases', interaction.guildId);
        if (!cases.length) return interaction.reply({ embeds: [infoEmbed(locale, t('modstats.empty', { locale }))], ephemeral: true });
        const map = {};
        for (const c of cases) map[c.modId] = (map[c.modId] || 0) + 1;
        const lines = Object.entries(map).sort((a, b) => b[1] - a[1]).slice(0, 10).map(([id, n]) => t('modstats.line', { locale, vars: { id, n } })).join('\n');
        return interaction.reply({ embeds: [infoEmbed(locale, lines)] });
    },
    "nick": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user', true);
        const nickname = interaction.options.getString('nickname');
        const member = await interaction.guild.members.fetch(user.id).catch(() => null);
        if (!member) return interaction.reply({ embeds: [errorEmbed(locale, t('common.member_not_found', { locale }))], ephemeral: true });
        try {
            await member.setNickname(nickname || null);
            return interaction.reply({ embeds: [successEmbed(locale, nickname ? t('nick.success', { locale, vars: { nick: nickname } }) : t('nick.reset', { locale }))] });
        } catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
    "note": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const modstore = require('../../utils/modstore');
        const user = interaction.options.getUser('user', true);
        const text = interaction.options.getString('text', true);
        const rec = modstore.push(client.database, 'notes', interaction.guildId, { userId: user.id, modId: interaction.user.id, text });
        modstore.push(client.database, 'cases', interaction.guildId, { action: 'note', userId: user.id, modId: interaction.user.id, reason: text });
        return interaction.reply({ embeds: [successEmbed(locale, t('note.success', { locale, vars: { user: user.tag } }) + ' (#' + rec.id + ')')] });
    },
    "notes": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const modstore = require('../../utils/modstore');
        const user = interaction.options.getUser('user', true);
        const list = modstore.all(client.database, 'notes', interaction.guildId).filter(w => w.userId === user.id);
        if (!list.length) return interaction.reply({ embeds: [infoEmbed(locale, t('notes.empty', { locale }))], ephemeral: true });
        const lines = list.map(w => t('notes.line', { locale, vars: { id: w.id, text: w.text, ts: w.ts } })).join('\n');
        return interaction.reply({ embeds: [infoEmbed(locale, lines)] });
    },
    "purge": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const amount = interaction.options.getInteger('amount', true);
        const user = interaction.options.getUser('user');
        if (amount < 1 || amount > 100) return interaction.reply({ embeds: [errorEmbed(locale, t('purge.invalid', { locale }))], ephemeral: true });
        try {
            const msgs = await interaction.channel.messages.fetch({ limit: amount });
            const list = user ? msgs.filter(m => m.author.id === user.id) : msgs;
            const deleted = await interaction.channel.bulkDelete(list, true).catch(() => null);
            return interaction.reply({ embeds: [successEmbed(locale, t('purge.success', { locale, vars: { n: deleted ? deleted.size : list.size } }))], ephemeral: true });
        } catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
    "reason": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const id = interaction.options.getInteger('id', true);
        const reason = interaction.options.getString('reason', true);
        const arr = client.database.get('cases-' + interaction.guildId) || [];
        const c = arr.find(x => x.id === id);
        if (!c) return interaction.reply({ embeds: [errorEmbed(locale, t('reason.not_found', { locale }))], ephemeral: true });
        c.reason = reason;
        client.database.set('cases-' + interaction.guildId, arr);
        return interaction.reply({ embeds: [successEmbed(locale, t('reason.success', { locale, vars: { id } }))] });
    },
    "report": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user', true);
        const text = interaction.options.getString('text', true);
        const { EmbedBuilder } = require('discord.js');
        const embed = new EmbedBuilder().setColor(0xffffff).setTitle('Report').setDescription('**' + user.tag + '**\n' + text).setTimestamp();
        const log = interaction.guild.channels.cache.find(c => c.name === 'mod-log' && c.isTextBased());
        if (log) { try { await log.send({ embeds: [embed] }); } catch {} }
        return interaction.reply({ embeds: [successEmbed(locale, t('report.success', { locale }))], ephemeral: true });
    },
    "slowmode": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const s = interaction.options.getInteger('seconds', true);
        if (s < 0 || s > 21600) return interaction.reply({ embeds: [errorEmbed(locale, t('slowmode.invalid', { locale }))], ephemeral: true });
        try {
            await interaction.channel.setRateLimitPerUser(s);
            return interaction.reply({ embeds: [successEmbed(locale, t(s === 0 ? 'slowmode.off' : 'slowmode.success', { locale, vars: { s } }))] });
        } catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
    "softban": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user', true);
        const reason = interaction.options.getString('reason') || 'No reason';
        const days = Math.min(7, Math.max(0, interaction.options.getInteger('days') ?? 1));
        try {
            await interaction.guild.members.ban(user.id, { reason, deleteMessageSeconds: days * 86400 });
            await interaction.guild.bans.remove(user.id, 'Softban: ' + reason).catch(() => null);
            return interaction.reply({ embeds: [successEmbed(locale, t('softban.success', { locale, vars: { user: user.tag } }))] });
        } catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
    "tempban": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user', true);
        const minutes = interaction.options.getInteger('minutes', true);
        const reason = interaction.options.getString('reason') || 'No reason';
        if (minutes < 1 || minutes > 525600) return interaction.reply({ embeds: [errorEmbed(locale, t('tempban.invalid', { locale }))], ephemeral: true });
        try {
            await interaction.guild.members.ban(user.id, { reason: 'Tempban ' + minutes + 'm: ' + reason });
            require('../../utils/scheduler').scheduleKind(client, interaction.guildId, 'tempban', { userId: user.id, reason }, Date.now() + minutes * 60000);
            return interaction.reply({ embeds: [successEmbed(locale, t('tempban.success', { locale, vars: { user: user.tag, duration: minutes + 'm' } }))] });
        } catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
    "tempmute": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user', true);
        const minutes = interaction.options.getInteger('minutes', true);
        const reason = interaction.options.getString('reason') || 'No reason';
        const member = await interaction.guild.members.fetch(user.id).catch(() => null);
        if (!member) return interaction.reply({ embeds: [errorEmbed(locale, t('common.member_not_found', { locale }))], ephemeral: true });
        try { await member.timeout(Math.min(40320, Math.max(1, minutes)) * 60000, reason); require('../../utils/scheduler').scheduleKind(client, interaction.guildId, 'tempmute', { userId: user.id, reason }, Date.now() + Math.min(40320, Math.max(1, minutes)) * 60000); return interaction.reply({ embeds: [successEmbed(locale, t('tempmute.success', { locale, vars: { user: user.tag, minutes } }))] }); }
        catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
    "timeout": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user', true);
        const min = interaction.options.getInteger('minutes') || 10;
        const member = await interaction.guild.members.fetch(user.id).catch(() => null);
        if (!member) return interaction.reply({ content: t('timeout.not_found', { locale }), ephemeral: true });
        try {
            await member.timeout(min * 60_000, 'Timeout via command');
            return interaction.reply({ content: t('timeout.success', { locale, vars: { user: user.tag, minutes: min } }) });
        } catch (e) {
            return interaction.reply({ content: t('mod_error', { locale, vars: { error: e.message || e } }), ephemeral: true });
        }
    },
    "unban": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const id = interaction.options.getString('id', true);
        const reason = interaction.options.getString('reason') || 'No reason';
        try {
            await interaction.guild.bans.remove(id, reason);
            return interaction.reply({ embeds: [successEmbed(locale, t('unban.success', { locale, vars: { user: id } }))] });
        } catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
    "unlock": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        try {
            await interaction.channel.permissionOverwrites.edit(interaction.guild.roles.everyone, { SendMessages: null });
            return interaction.reply({ embeds: [successEmbed(locale, t('lock.unlocked', { locale }))] });
        } catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
    "unmute": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const user = interaction.options.getUser('user', true);
        const member = await interaction.guild.members.fetch(user.id).catch(() => null);
        if (!member) return interaction.reply({ embeds: [errorEmbed(locale, t('common.member_not_found', { locale }))], ephemeral: true });
        try { await member.timeout(null); return interaction.reply({ embeds: [successEmbed(locale, t('unmute.success', { locale, vars: { user: user.tag } }))] }); }
        catch (e) { return interaction.reply({ embeds: [errorEmbed(locale, t('mod_error', { locale, vars: { error: e.message || e } }))], ephemeral: true }); }
    },
};

module.exports = new ApplicationCommand({
    command: {
        name: "mod", description: "🔨 Moderation commands.", type: 1,
        description_localizations: { 'pt-BR': "🔨 Comandos de moderação." },
        options: [
            {
                name: "ban",
                description: "🔨 Bans a member.",
                description_localizations: {"pt-BR":"🔨 Bane um membro."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Target member","description_localizations":{"pt-BR":"Membro alvo"},"type":6,"required":true},{"name":"reason","name_localizations":{"pt-BR":"motivo"},"description":"Reason","description_localizations":{"pt-BR":"Motivo"},"type":3}],
            },
            {
                name: "case",
                description: "🔨 Shows a moderation case by ID.",
                description_localizations: {"pt-BR":"🔨 Mostra um caso de moderação por ID."},
                type: 1,
                options: [{"name":"id","description":"Case ID","description_localizations":{"pt-BR":"ID do caso"},"type":4,"required":true}],
            },
            {
                name: "clearwarn",
                description: "🔨 Clears one or all warnings.",
                description_localizations: {"pt-BR":"🔨 Remove uma ou todas advertências."},
                type: 1,
                options: [{"name":"id","description":"Warning ID (empty = all of the user)","description_localizations":{"pt-BR":"ID da advertência (vazio = todas do usuário)"},"type":4},{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Target member (for all)","description_localizations":{"pt-BR":"Membro alvo (p/ todas)"},"type":6}],
            },
            {
                name: "hackban",
                description: "🔨 Bans a user not in the server by ID.",
                description_localizations: {"pt-BR":"🔨 Bane por ID um usuário fora do servidor."},
                type: 1,
                options: [{"name":"id","description":"User ID","description_localizations":{"pt-BR":"ID do usuário"},"type":3,"required":true},{"name":"reason","name_localizations":{"pt-BR":"motivo"},"description":"Reason","description_localizations":{"pt-BR":"Motivo"},"type":3}],
            },
            {
                name: "history",
                description: "🔨 Shows warns and notes history of a member.",
                description_localizations: {"pt-BR":"🔨 Mostra histórico (warns+notas) de um membro."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Target member","description_localizations":{"pt-BR":"Membro alvo"},"type":6,"required":true}],
            },
            {
                name: "kick",
                description: "🔨 Kicks a member.",
                description_localizations: {"pt-BR":"🔨 Expulsa um membro."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Target member","description_localizations":{"pt-BR":"Membro alvo"},"type":6,"required":true},{"name":"reason","name_localizations":{"pt-BR":"motivo"},"description":"Reason","description_localizations":{"pt-BR":"Motivo"},"type":3}],
            },
            {
                name: "lock",
                description: "🔒 Locks the channel (@everyone cannot send).",
                description_localizations: {"pt-BR":"🔒 Tranca o canal (@everyone não envia)."},
                type: 1,
                options: [],
            },
            {
                name: "lockdown",
                description: "🔒 Locks or unlocks all text channels.",
                description_localizations: {"pt-BR":"🔒 Tranca/destranca todos os canais de texto."},
                type: 1,
                options: [{"name":"state","name_localizations":{"pt-BR":"estado"},"description":"on or off","description_localizations":{"pt-BR":"on ou off"},"type":3,"required":true,"choices":[{"name":"on","value":"on"},{"name":"off","value":"off"}]}],
            },
            {
                name: "massban",
                description: "🔨 Bans multiple users by ID (space separated).",
                description_localizations: {"pt-BR":"🔨 Bane vários usuários por ID (separados por espaço)."},
                type: 1,
                options: [{"name":"ids","description":"Space separated user IDs","description_localizations":{"pt-BR":"IDs separados por espaço"},"type":3,"required":true},{"name":"reason","name_localizations":{"pt-BR":"motivo"},"description":"Reason","description_localizations":{"pt-BR":"Motivo"},"type":3}],
            },
            {
                name: "modlog",
                description: "🔨 Shows recent moderation cases.",
                description_localizations: {"pt-BR":"🔨 Mostra casos recentes de moderação."},
                type: 1,
                options: [{"name":"limit","name_localizations":{"pt-BR":"limite"},"description":"How many (max 10)","description_localizations":{"pt-BR":"Quantos (máx 10)"},"type":4}],
            },
            {
                name: "modstats",
                description: "🔨 Shows moderation action ranking by staff.",
                description_localizations: {"pt-BR":"🔨 Mostra ranking de ações por staff."},
                type: 1,
                options: [],
            },
            {
                name: "nick",
                description: "✏️ Sets or removes a member nickname.",
                description_localizations: {"pt-BR":"✏️ Define ou remove apelido de membro."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Target member","description_localizations":{"pt-BR":"Membro alvo"},"type":6,"required":true},{"name":"nickname","name_localizations":{"pt-BR":"apelido"},"description":"New nickname (empty = remove)","description_localizations":{"pt-BR":"Novo apelido (vazio = remover)"},"type":3}],
            },
            {
                name: "note",
                description: "🔨 Adds a staff note to a member.",
                description_localizations: {"pt-BR":"🔨 Adiciona nota de staff a um membro."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Target member","description_localizations":{"pt-BR":"Membro alvo"},"type":6,"required":true},{"name":"text","name_localizations":{"pt-BR":"texto"},"description":"Note text","description_localizations":{"pt-BR":"Texto da nota"},"type":3,"required":true}],
            },
            {
                name: "notes",
                description: "🔨 Lists staff notes of a member.",
                description_localizations: {"pt-BR":"🔨 Lista notas de staff de um membro."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Target member","description_localizations":{"pt-BR":"Membro alvo"},"type":6,"required":true}],
            },
            {
                name: "purge",
                description: "🧹 Deletes messages (1-100, optional user filter).",
                description_localizations: {"pt-BR":"🧹 Apaga mensagens (1-100, filtro opcional)."},
                type: 1,
                options: [{"name":"amount","name_localizations":{"pt-BR":"quantidade"},"description":"Amount 1-100","description_localizations":{"pt-BR":"Quantidade 1-100"},"type":4,"required":true},{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Only this user","description_localizations":{"pt-BR":"Só deste usuário"},"type":6}],
            },
            {
                name: "reason",
                description: "🔨 Edits the reason of a case.",
                description_localizations: {"pt-BR":"🔨 Edita o motivo de um caso."},
                type: 1,
                options: [{"name":"id","description":"Case ID","description_localizations":{"pt-BR":"ID do caso"},"type":4,"required":true},{"name":"reason","name_localizations":{"pt-BR":"motivo"},"description":"New reason","description_localizations":{"pt-BR":"Novo motivo"},"type":3,"required":true}],
            },
            {
                name: "report",
                description: "🚨 Reports a member to staff.",
                description_localizations: {"pt-BR":"🚨 Denuncia um membro para a staff."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Reported member","description_localizations":{"pt-BR":"Membro denunciado"},"type":6,"required":true},{"name":"text","name_localizations":{"pt-BR":"texto"},"description":"What happened","description_localizations":{"pt-BR":"O que aconteceu"},"type":3,"required":true}],
            },
            {
                name: "slowmode",
                description: "🐢 Sets slowmode seconds (0 = off).",
                description_localizations: {"pt-BR":"🐢 Define slowmode em segundos (0 = off)."},
                type: 1,
                options: [{"name":"seconds","name_localizations":{"pt-BR":"segundos"},"description":"0-21600","description_localizations":{"pt-BR":"0-21600"},"type":4,"required":true}],
            },
            {
                name: "softban",
                description: "🔨 Soft-bans a member (ban + immediate unban).",
                description_localizations: {"pt-BR":"🔨 Soft-bane um membro (bane e desbane)."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Target member","description_localizations":{"pt-BR":"Membro alvo"},"type":6,"required":true},{"name":"reason","name_localizations":{"pt-BR":"motivo"},"description":"Reason","description_localizations":{"pt-BR":"Motivo"},"type":3},{"name":"days","name_localizations":{"pt-BR":"dias"},"description":"Days of messages to delete (0-7)","description_localizations":{"pt-BR":"Dias de mensagens p/ apagar (0-7)"},"type":4}],
            },
            {
                name: "tempban",
                description: "🔨 Temporarily bans a member.",
                description_localizations: {"pt-BR":"🔨 Bane temporariamente um membro."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Target member","description_localizations":{"pt-BR":"Membro alvo"},"type":6,"required":true},{"name":"minutes","name_localizations":{"pt-BR":"minutos"},"description":"Duration in minutes","description_localizations":{"pt-BR":"Duração em minutos"},"type":4,"required":true},{"name":"reason","name_localizations":{"pt-BR":"motivo"},"description":"Reason","description_localizations":{"pt-BR":"Motivo"},"type":3}],
            },
            {
                name: "tempmute",
                description: "🔨 Mutes a member for some minutes.",
                description_localizations: {"pt-BR":"🔨 Silencia um membro por minutos."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Target member","description_localizations":{"pt-BR":"Membro alvo"},"type":6,"required":true},{"name":"minutes","name_localizations":{"pt-BR":"minutos"},"description":"Minutes (max 40320)","description_localizations":{"pt-BR":"Minutos (máx 40320)"},"type":4,"required":true},{"name":"reason","name_localizations":{"pt-BR":"motivo"},"description":"Reason","description_localizations":{"pt-BR":"Motivo"},"type":3}],
            },
            {
                name: "timeout",
                description: "🔨 Times out a member.",
                description_localizations: {"pt-BR":"🔨 Aplica timeout em um membro."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Target member","description_localizations":{"pt-BR":"Membro alvo"},"type":6,"required":true},{"name":"minutes","name_localizations":{"pt-BR":"minutos"},"description":"Minutes (1-40320)","description_localizations":{"pt-BR":"Minutos (1-40320)"},"type":4}],
            },
            {
                name: "unban",
                description: "🔨 Unbans a user by ID.",
                description_localizations: {"pt-BR":"🔨 Desbane um usuário por ID."},
                type: 1,
                options: [{"name":"id","name_localizations":{"pt-BR":"id"},"description":"User ID to unban","description_localizations":{"pt-BR":"ID do usuário"},"type":3,"required":true},{"name":"reason","name_localizations":{"pt-BR":"motivo"},"description":"Reason","description_localizations":{"pt-BR":"Motivo"},"type":3}],
            },
            {
                name: "unlock",
                description: "🔓 Unlocks the channel.",
                description_localizations: {"pt-BR":"🔓 Destranca o canal."},
                type: 1,
                options: [],
            },
            {
                name: "unmute",
                description: "🔨 Unmutes a member.",
                description_localizations: {"pt-BR":"🔨 Remove o mute de um membro."},
                type: 1,
                options: [{"name":"user","name_localizations":{"pt-BR":"usuario"},"description":"Target member","description_localizations":{"pt-BR":"Membro alvo"},"type":6,"required":true}],
            },
        ],
    },
    /**
     * @param {DiscordBot} client
     * @param {ChatInputCommandInteraction} interaction
     */
    run: async (client, interaction) => {
        const sub = interaction.options.getSubcommand();
        const need = SUB_PERMS[sub];
        if (need) {
            let ok = false;
            try { ok = !!interaction.memberPermissions && interaction.memberPermissions.has(BigInt(need)); } catch { ok = false; }
            if (!ok) {
                const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
                return interaction.reply({ content: t('handler.missing_permissions', { locale }), ephemeral: true });
            }
        }
        const fn = handlers[sub];
        if (!fn) {
            return interaction.reply({ content: 'Unknown subcommand: ' + sub, ephemeral: true });
        }
        return fn(client, interaction);
    },
}).toJSON();
