// Grouped from 2 flat commands (Voice/slashcommand-tempvoice-remove.js, Voice/slashcommand-tempvoice-setup.js). Generated by scripts/group-commands.js.
const { ChatInputCommandInteraction } = require('discord.js');
const DiscordBot = require('../../client/DiscordBot');
const ApplicationCommand = require('../../structure/ApplicationCommand');
const { t, resolveLocale } = require('../../utils/i18n');
const { PermissionFlagsBits } = require('discord.js');
const { successEmbed, errorEmbed, infoEmbed } = require('../../utils/embeds');

const SUB_PERMS = {
    "tempvoice-remove": "16",
    "tempvoice-setup": "16",
};

const handlers = {
    "tempvoice-remove": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        client.database.set('tempvoice-' + interaction.guildId, null);
        return interaction.reply({ embeds: [successEmbed(locale, t('tempvoice.off', { locale }))] });
    },
    "tempvoice-setup": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const ch = interaction.options.getChannel('channel', true);
        client.database.set('tempvoice-' + interaction.guildId, { lobby: ch.id });
        return interaction.reply({ embeds: [successEmbed(locale, t('tempvoice.ok', { locale }) + ' TODO: create/delete engine on voiceStateUpdate.')] });
    },
};

module.exports = new ApplicationCommand({
    command: {
        name: "voice", description: "🔊 Temporary voice channels.", type: 1,
        description_localizations: { 'pt-BR': "🔊 Canais de voz temporários." },
        default_member_permissions: "16",
        options: [
            {
                name: "tempvoice-remove",
                description: "🔊 Disables temp voice.",
                description_localizations: {"pt-BR":"🔊 Desliga voz temporária."},
                type: 1,
                options: [],
            },
            {
                name: "tempvoice-setup",
                description: "🔊 Sets the join-to-create voice channel.",
                description_localizations: {"pt-BR":"🔊 Define canal p/ criar calls temp."},
                type: 1,
                options: [{"name":"channel","name_localizations":{"pt-BR":"canal"},"description":"Lobby voice channel","description_localizations":{"pt-BR":"Canal de voz lobby"},"type":7,"required":true}],
            },
        ],
    },
    /**
     * @param {DiscordBot} client
     * @param {ChatInputCommandInteraction} interaction
     */
    run: async (client, interaction) => {
        const sub = interaction.options.getSubcommand();
        const need = SUB_PERMS[sub];
        if (need) {
            let ok = false;
            try { ok = !!interaction.memberPermissions && interaction.memberPermissions.has(BigInt(need)); } catch { ok = false; }
            if (!ok) {
                const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
                return interaction.reply({ content: t('handler.missing_permissions', { locale }), ephemeral: true });
            }
        }
        const fn = handlers[sub];
        if (!fn) {
            return interaction.reply({ content: 'Unknown subcommand: ' + sub, ephemeral: true });
        }
        return fn(client, interaction);
    },
}).toJSON();
