// Grouped from 3 flat commands (Information/slashcommand-help.js, Admin/slashcommand-language.js, Utility/slashcommand-ping.js). Generated by scripts/group-commands.js.
const { ChatInputCommandInteraction } = require('discord.js');
const DiscordBot = require('../../client/DiscordBot');
const ApplicationCommand = require('../../structure/ApplicationCommand');
const { t, resolveLocale } = require('../../utils/i18n');
const { PermissionFlagsBits } = require('discord.js');
const { setGuildLocale, getGuildLocale, getSupportedLocales } = require('../../utils/i18n');

const SUB_PERMS = {
    "language": "32",
};

const handlers = {
    "help": async (client, interaction) => {
        await interaction.reply({
            content: `${client.collection.application_commands.map((cmd) => '\`/' + cmd.command.name + '\`').join(', ')}`
        });
    },
    "language": async (client, interaction) => {
        if (!interaction.guildId) {
            return interaction.reply({ content: t('handler.missing_permissions', { locale: resolveLocale({ discordLocale: interaction.locale }) }), ephemeral: true });
        }

        const novo = interaction.options.getString('new');
        if (!novo) {
            const current = getGuildLocale(interaction.guildId) || resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
            return interaction.reply({ content: t('language.current', { locale: current, vars: { locale: current } }), ephemeral: true });
        }

        const saved = setGuildLocale(interaction.guildId, novo);
        return interaction.reply({ content: t('language.updated', { locale: saved, vars: { locale: saved } }), ephemeral: true });
    },
    "ping": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        await interaction.reply({
            content: t('ping.response', { locale, vars: { ping: client.ws.ping } })
        });
    },
};

module.exports = new ApplicationCommand({
    command: {
        name: "info", description: "ℹ️ Info and help.", type: 1,
        description_localizations: { 'pt-BR': "ℹ️ Informações e ajuda." },
        options: [
            {
                name: "help",
                description: "ℹ️ Replies with a list of available application commands.",
                description_localizations: {"pt-BR":"ℹ️ Responde com a lista de comandos disponíveis."},
                type: 1,
                options: [],
            },
            {
                name: "language",
                name_localizations: {"pt-BR":"idioma"},
                description: "🛠️ Sets the bot language in this server.",
                description_localizations: {"pt-BR":"🛠️ Define o idioma do bot neste servidor."},
                type: 1,
                options: [{"name":"new","name_localizations":{"pt-BR":"novo"},"description":"New language (empty = shows current).","description_localizations":{"pt-BR":"Novo idioma (vazio = mostra o atual)."},"type":3,"required":false,"choices":[{"name":"Português","name_localizations":{"pt-BR":"Português"},"value":"pt-BR"},{"name":"English","name_localizations":{"pt-BR":"Inglês"},"value":"en-US"}]}],
            },
            {
                name: "ping",
                description: "ℹ️ Replies with Pong!",
                description_localizations: {"pt-BR":"ℹ️ Responde com Pong!"},
                type: 1,
                options: [],
            },
        ],
    },
    options: { cooldown: 10000 },
    /**
     * @param {DiscordBot} client
     * @param {ChatInputCommandInteraction} interaction
     */
    run: async (client, interaction) => {
        const sub = interaction.options.getSubcommand();
        const need = SUB_PERMS[sub];
        if (need) {
            let ok = false;
            try { ok = !!interaction.memberPermissions && interaction.memberPermissions.has(BigInt(need)); } catch { ok = false; }
            if (!ok) {
                const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
                return interaction.reply({ content: t('handler.missing_permissions', { locale }), ephemeral: true });
            }
        }
        const fn = handlers[sub];
        if (!fn) {
            return interaction.reply({ content: 'Unknown subcommand: ' + sub, ephemeral: true });
        }
        return fn(client, interaction);
    },
}).toJSON();
