// Grouped from 4 flat commands (Suggest/slashcommand-suggest-approve.js, Suggest/slashcommand-suggest-deny.js, Suggest/slashcommand-suggest-list.js, Suggest/slashcommand-suggest.js). Generated by scripts/group-commands.js.
const { ChatInputCommandInteraction } = require('discord.js');
const DiscordBot = require('../../client/DiscordBot');
const ApplicationCommand = require('../../structure/ApplicationCommand');
const { t, resolveLocale } = require('../../utils/i18n');
const { PermissionFlagsBits } = require('discord.js');
const { successEmbed, errorEmbed, infoEmbed } = require('../../utils/embeds');

const SUB_PERMS = {
    "suggest-approve": "32",
    "suggest-deny": "32",
};

const handlers = {
    "suggest": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const modstore = require('../../utils/modstore');
        const text = interaction.options.getString('text', true);
        const rec = modstore.push(client.database, 'suggests', interaction.guildId, { userId: interaction.user.id, text, status: 'open' });
        return interaction.reply({ embeds: [successEmbed(locale, t('suggest.sent', { locale, vars: { id: rec.id } }))] });
    },
    "suggest-approve": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const id = interaction.options.getInteger('id', true);
        const arr = client.database.get('suggests-' + interaction.guildId) || [];
        const s = arr.find(x => x.id === id);
        if (!s) return interaction.reply({ embeds: [errorEmbed(locale, t('suggest.notfound', { locale }))], ephemeral: true });
        s.status = 'approved';
        client.database.set('suggests-' + interaction.guildId, arr);
        return interaction.reply({ embeds: [successEmbed(locale, t('suggest.updated', { locale, vars: { id, status: 'approved' } }))] });
    },
    "suggest-deny": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const id = interaction.options.getInteger('id', true);
        const arr = client.database.get('suggests-' + interaction.guildId) || [];
        const s = arr.find(x => x.id === id);
        if (!s) return interaction.reply({ embeds: [errorEmbed(locale, t('suggest.notfound', { locale }))], ephemeral: true });
        s.status = 'denied';
        client.database.set('suggests-' + interaction.guildId, arr);
        return interaction.reply({ embeds: [successEmbed(locale, t('suggest.updated', { locale, vars: { id, status: 'denied' } }))] });
    },
    "suggest-list": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const modstore = require('../../utils/modstore');
        const list = modstore.all(client.database, 'suggests', interaction.guildId).slice(-10).reverse();
        if (!list.length) return interaction.reply({ embeds: [infoEmbed(locale, t('suggest.empty', { locale }))], ephemeral: true });
        return interaction.reply({ embeds: [infoEmbed(locale, list.map(s => t('suggest.line', { locale, vars: { id: s.id, status: s.status, text: String(s.text).slice(0, 100) } })).join('\n'))] });
    },
};

module.exports = new ApplicationCommand({
    command: {
        name: "suggest", description: "💡 Suggestions.", type: 1,
        description_localizations: { 'pt-BR': "💡 Sugestões." },
        options: [
            {
                name: "suggest",
                description: "💡 Sends a suggestion.",
                description_localizations: {"pt-BR":"💡 Envia uma sugestão."},
                type: 1,
                options: [{"name":"text","name_localizations":{"pt-BR":"texto"},"description":"Suggestion","description_localizations":{"pt-BR":"Sugestão"},"type":3,"required":true}],
            },
            {
                name: "suggest-approve",
                description: "💡 Approves a suggestion.",
                description_localizations: {"pt-BR":"💡 Aprova uma sugestão."},
                type: 1,
                options: [{"name":"id","description":"Suggestion ID","description_localizations":{"pt-BR":"ID da sugestão"},"type":4,"required":true}],
            },
            {
                name: "suggest-deny",
                description: "💡 Denies a suggestion.",
                description_localizations: {"pt-BR":"💡 Rejeita uma sugestão."},
                type: 1,
                options: [{"name":"id","description":"Suggestion ID","description_localizations":{"pt-BR":"ID da sugestão"},"type":4,"required":true}],
            },
            {
                name: "suggest-list",
                description: "💡 Lists suggestions.",
                description_localizations: {"pt-BR":"💡 Lista sugestões."},
                type: 1,
                options: [],
            },
        ],
    },
    /**
     * @param {DiscordBot} client
     * @param {ChatInputCommandInteraction} interaction
     */
    run: async (client, interaction) => {
        const sub = interaction.options.getSubcommand();
        const need = SUB_PERMS[sub];
        if (need) {
            let ok = false;
            try { ok = !!interaction.memberPermissions && interaction.memberPermissions.has(BigInt(need)); } catch { ok = false; }
            if (!ok) {
                const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
                return interaction.reply({ content: t('handler.missing_permissions', { locale }), ephemeral: true });
            }
        }
        const fn = handlers[sub];
        if (!fn) {
            return interaction.reply({ content: 'Unknown subcommand: ' + sub, ephemeral: true });
        }
        return fn(client, interaction);
    },
}).toJSON();
