// Grouped from 2 flat commands (Sticky/slashcommand-sticky-remove.js, Sticky/slashcommand-sticky-set.js). Generated by scripts/group-commands.js.
const { ChatInputCommandInteraction } = require('discord.js');
const DiscordBot = require('../../client/DiscordBot');
const ApplicationCommand = require('../../structure/ApplicationCommand');
const { t, resolveLocale } = require('../../utils/i18n');
const { PermissionFlagsBits } = require('discord.js');
const { successEmbed, errorEmbed, infoEmbed } = require('../../utils/embeds');

const SUB_PERMS = {
    "sticky-remove": "8192",
    "sticky-set": "8192",
};

const handlers = {
    "sticky-remove": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const all = client.database.get('sticky-' + interaction.guildId) || {};
        delete all[interaction.channelId];
        client.database.set('sticky-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('sticky.removed', { locale }))] });
    },
    "sticky-set": async (client, interaction) => {
        const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
        const text = interaction.options.getString('text', true);
        const all = client.database.get('sticky-' + interaction.guildId) || {};
        const m = await interaction.channel.send(text.slice(0, 1900));
        all[interaction.channelId] = { text, lastId: m.id };
        client.database.set('sticky-' + interaction.guildId, all);
        return interaction.reply({ embeds: [successEmbed(locale, t('sticky.ok', { locale }) + ' TODO: repost engine on message.')] , ephemeral: true });
    },
};

module.exports = new ApplicationCommand({
    command: {
        name: "sticky", description: "📌 Sticky messages.", type: 1,
        description_localizations: { 'pt-BR': "📌 Mensagens fixas." },
        default_member_permissions: "8192",
        options: [
            {
                name: "sticky-remove",
                description: "📌 Removes sticky from this channel.",
                description_localizations: {"pt-BR":"📌 Remove sticky deste canal."},
                type: 1,
                options: [],
            },
            {
                name: "sticky-set",
                description: "📌 Sets a sticky message in this channel.",
                description_localizations: {"pt-BR":"📌 Define msg fixa neste canal."},
                type: 1,
                options: [{"name":"text","name_localizations":{"pt-BR":"texto"},"description":"Message","description_localizations":{"pt-BR":"Mensagem"},"type":3,"required":true}],
            },
        ],
    },
    /**
     * @param {DiscordBot} client
     * @param {ChatInputCommandInteraction} interaction
     */
    run: async (client, interaction) => {
        const sub = interaction.options.getSubcommand();
        const need = SUB_PERMS[sub];
        if (need) {
            let ok = false;
            try { ok = !!interaction.memberPermissions && interaction.memberPermissions.has(BigInt(need)); } catch { ok = false; }
            if (!ok) {
                const locale = resolveLocale({ guildId: interaction.guildId, discordLocale: interaction.locale });
                return interaction.reply({ content: t('handler.missing_permissions', { locale }), ephemeral: true });
            }
        }
        const fn = handlers[sub];
        if (!fn) {
            return interaction.reply({ content: 'Unknown subcommand: ' + sub, ephemeral: true });
        }
        return fn(client, interaction);
    },
}).toJSON();
